"use client"

import React, { createContext, useContext, useState } from "react"

export type Language = "english" | "tamil" | "hindi" | "telugu" | "kannada" | "malayalam"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

type TranslationKey = keyof typeof translations.english

const translations = {
  english: {
    // ... existing code ...
    "contracts.title": "Creating and Managing Contracts",
    "contracts.description": "Learn how to create, view, and manage agricultural contracts",
    "contracts.create.title": "Creating a New Contract",
    "contracts.create.step1.title": "Go to Contract Creation",
    "contracts.create.step1.description": 'From your dashboard, click on "Contracts" in the sidebar, then select "Create New Contract".',
    "contracts.create.step2.title": "Fill Contract Details",
    "contracts.create.step2.description": "Fill in all required fields in the contract form:",
    "contracts.create.step2.field1": "Contract Title",
    "contracts.create.step2.field2": "Contract Type (Fixed Price, Revenue Share, etc.)",
    "contracts.create.step2.field3": "Start and End Dates",
    "contracts.create.step2.field4": "Crop Details (Type, Quantity, Quality Standards)",
    "contracts.create.step2.field5": "Price Information",
    "contracts.create.step2.field6": "Payment Terms",
    "contracts.create.step2.field7": "Delivery Schedule",
    "contracts.create.step3.title": "Add Special Terms (Optional)",
    "contracts.create.step3.description": "Add any specific special terms or conditions to your contract.",
    "contracts.create.step4.title": "Review and Submit",
    "contracts.create.step4.description": 'Carefully review all contract details before clicking "Create Contract".',
    "contracts.manage.title": "Viewing and Managing Contracts",
    "contracts.manage.description": "To view your current contracts:",
    "contracts.manage.step1": 'Go to "Contracts" > "Contract List" in the sidebar',
    "contracts.manage.step2": "Use filters to sort contracts by status, date, or type",
    "contracts.manage.step3": "Click on any contract to view its details",
    "contracts.manage.step4": "From the contract details page, you can:",
    "contracts.manage.step4.action1": "Download contract document",
    "contracts.manage.step4.action2": "View contract timeline and history",
    "contracts.manage.step4.action3": "Edit contract (if allowed)",
    "contracts.manage.step4.action4": "Terminate contract (if needed)",

    "marketplace.title": "Using the Marketplace",
    "marketplace.description": "Learn how to browse, create, and respond to marketplace listings",
    "marketplace.browse.title": "Browsing Listings",
    "marketplace.browse.description": "Find agricultural products and contracts in the marketplace:",
    "marketplace.browse.step1": 'Go to "Marketplace" in the main navigation',
    "marketplace.browse.step2": "Use filters to narrow your search:",
    "marketplace.browse.filter1": "Product Type",
    "marketplace.browse.filter2": "Location",
    "marketplace.browse.filter3": "Price Range",
    "marketplace.browse.filter4": "Availability Date",
    "marketplace.browse.step3": "Click on listings to view full details",
    "marketplace.create.title": "Creating Listings",
    "marketplace.create.description": "Create new marketplace listings for your products:",
    "marketplace.create.step1": 'Click "Create Listing" in the marketplace',
    "marketplace.create.step2": "Fill in the listing details:",
    "marketplace.create.field1": "Product Name and Description",
    "marketplace.create.field2": "Quantity Available",
    "marketplace.create.field3": "Price per Unit",
    "marketplace.create.field4": "Location",
    "marketplace.create.field5": "Available Dates",
    "marketplace.create.field6": "Quality Specifications",
    "marketplace.create.field7": "Images (if applicable)",
    "marketplace.create.step3": "Set your preferred contact method",
    "marketplace.create.step4": "Review and publish your listing",
    "marketplace.create.step5": "Respond to inquiries from potential buyers",
    "marketplace.respond.title": "Responding to Listings",
    "marketplace.respond.description": "Interact with marketplace listings:",
    "marketplace.respond.step1": "View listing details",
    "marketplace.respond.step2": "Check availability and pricing",
    "marketplace.respond.step3": "Contact the seller through:",
    "marketplace.respond.action1": "Direct messaging",
    "marketplace.respond.action2": "Email",
    "marketplace.respond.action3": "Phone (if provided)",
    "verification.title": "Verification",
    "verification.description": "Verify your account",
    "verification.importance.title": "Importance of Verification",
    "verification.importance.description": "Why you should verify your account:",
    "verification.importance.reason1": "Build trust with other users",
    "verification.importance.reason2": "Access premium features",
    "verification.importance.reason3": "Ensure secure transactions",
    "verification.importance.reason4": "Protect your account",
    "verification.steps.title": "Verification Steps",
    "verification.steps.description": "Follow these steps to verify your account:",
    "verification.steps.step1": "Go to your profile settings",
    "verification.steps.step2": "Click on 'Verify Account'",
    "verification.steps.step3": "Upload required documents:",
    "verification.steps.doc1": "Government ID",
    "verification.steps.doc2": "Proof of address",
    "verification.steps.doc3": "Business registration (if applicable)",
    "verification.steps.step4": "Submit for review",
    "verification.steps.step5": "Wait for approval (usually 1-2 business days)",
    // ... existing code ...
  },
  tamil: {
    // ... existing code ...
    "contracts.title": "ஒப்பந்தங்கள்",
    "contracts.description": "ஒப்பந்தங்களை உருவாக்கவும் மற்றும் நிர்வகிக்கவும்",
    "contracts.create.title": "ஒப்பந்தத்தை உருவாக்குதல்",
    "contracts.create.description": "புதிய விவசாய ஒப்பந்தத்தை உருவாக்க இந்த படிகளைப் பின்பற்றவும்",
    "contracts.create.step1.title": "படி 1: ஒப்பந்த விவரங்களை உள்ளிடவும்",
    "contracts.create.step1.description": "ஒப்பந்தத்தின் அடிப்படை தகவல்களை உள்ளிடவும்",
    "contracts.create.step2.title": "படி 2: ஒப்பந்த விவரங்களை உள்ளிடவும்",
    "contracts.create.step2.description": "ஒப்பந்தத்தின் விரிவான தகவல்களை உள்ளிடவும்",
    "contracts.create.step2.field1": "ஒப்பந்தத்தின் பெயர்",
    "contracts.create.step2.field2": "ஒப்பந்த வகை",
    "contracts.create.step2.field3": "தொடக்க மற்றும் முடிவு தேதிகள்",
    "contracts.create.step2.field4": "பயிர் விவரங்கள் (வகை, அளவு, தர தரநிலைகள்)",
    "contracts.create.step2.field5": "விலை விவரங்கள்",
    "contracts.create.step2.field6": "பணம் செலுத்தும் விதிமுறைகள்",
    "contracts.create.step2.field7": "விநியோக அட்டவணை",
    "contracts.create.step3.title": "சிறப்பு விதிமுறைகளை சேர்க்கவும் (விருப்பத்தேர்வு)",
    "contracts.create.step3.description": "உங்கள் ஒப்பந்தத்திற்கு எந்தவொரு சிறப்பு விதிமுறைகள் அல்லது நிபந்தனைகளை சேர்க்கவும்",
    "contracts.create.step4.title": "மதிப்பாய்வு செய்து சமர்ப்பிக்கவும்",
    "contracts.create.step4.description": "ஒப்பந்தத்தை உருவாக்கவும்",
    "contracts.manage.title": "ஒப்பந்தங்களை நிர்வகித்தல்",
    "contracts.manage.description": "உங்கள் ஒப்பந்தங்களை பார்வையிடவும் மற்றும் நிர்வகிக்கவும்",
    "contracts.manage.step1": "ஒப்பந்தங்கள் பக்கத்திற்குச் செல்லவும்",
    "contracts.manage.step2": "ஒப்பந்தங்களின் பட்டியலைப் பார்வையிடவும்",
    "contracts.manage.step3": "எந்தவொரு ஒப்பந்தத்தையும் கிளிக் செய்து அதன் விவரங்களைப் பார்வையிடவும்",
    "contracts.manage.step4": "ஒப்பந்த விவரங்கள் பக்கத்திலிருந்து, நீங்கள்:",
    "contracts.manage.step4.action1": "ஒப்பந்த ஆவணத்தை பதிவிறக்கவும்",
    "contracts.manage.step4.action2": "ஒப்பந்த காலவரிசை மற்றும் வரலாற்றைப் பார்வையிடவும்",
    "contracts.manage.step4.action3": "ஒப்பந்தத்தை திருத்தவும் (அனுமதிக்கப்பட்டால்)",
    "contracts.manage.step4.action4": "ஒப்பந்தத்தை முடிக்கவும் (தேவைப்பட்டால்)",

    "marketplace.title": "சந்தையைப் பயன்படுத்துதல்",
    "marketplace.description": "சந்தை பட்டியல்களை உலாவவும், உருவாக்கவும் மற்றும் பதிலளிக்கவும் கற்றுக்கொள்ளுங்கள்",
    "marketplace.browse.title": "பட்டியல்களை உலாவுதல்",
    "marketplace.browse.description": "சந்தையில் விவசாய பொருட்கள் மற்றும் ஒப்பந்தங்களைக் கண்டறியவும்:",
    "marketplace.browse.step1": "முக்கிய வழிசெலுத்தலில் 'சந்தை'க்குச் செல்லவும்",
    "marketplace.browse.step2": "உங்கள் தேடலை குறைக்க வடிகட்டிகளைப் பயன்படுத்தவும்:",
    "marketplace.browse.filter1": "பொருள் வகை",
    "marketplace.browse.filter2": "இருப்பிடம்",
    "marketplace.browse.filter3": "விலை வரம்பு",
    "marketplace.browse.filter4": "கிடைக்கும் தேதி",
    "marketplace.browse.step3": "முழு விவரங்களைப் பார்வையிட பட்டியல்களைக் கிளிக் செய்யவும்",
    "marketplace.create.title": "பட்டியல்களை உருவாக்குதல்",
    "marketplace.create.description": "உங்கள் பொருட்களுக்கான புதிய சந்தை பட்டியல்களை உருவாக்கவும்:",
    "marketplace.create.step1": "சந்தையில் 'பட்டியல் உருவாக்கு' என்பதைக் கிளிக் செய்யவும்",
    "marketplace.create.step2": "பட்டியல் விவரங்களை நிரப்பவும்:",
    "marketplace.create.field1": "பொருள் பெயர் மற்றும் விளக்கம்",
    "marketplace.create.field2": "கிடைக்கும் அளவு",
    "marketplace.create.field3": "ஒரு அலகுக்கான விலை",
    "marketplace.create.field4": "இருப்பிடம்",
    "marketplace.create.field5": "கிடைக்கும் தேதிகள்",
    "marketplace.create.field6": "தர விவரக்குறிப்புகள்",
    "marketplace.create.field7": "படங்கள் (பொருந்துமானால்)",
    "marketplace.create.step3": "உங்கள் விருப்பமான தொடர்பு முறையை அமைக்கவும்",
    "marketplace.create.step4": "உங்கள் பட்டியலை மதிப்பாய்வு செய்து வெளியிடவும்",
    "marketplace.create.step5": "உங்கள் பட்டியலை வெளியிடவும்",
    "marketplace.respond.title": "பட்டியல்களுக்கு பதிலளித்தல்",
    "marketplace.respond.description": "சந்தை பட்டியல்களுடன் தொடர்பு கொள்ளவும்:",
    "marketplace.respond.step1": "பட்டியல் விவரங்களைப் பார்வையிடவும்",
    "marketplace.respond.step2": "கிடைக்கும் தன்மை மற்றும் விலைகளை சரிபார்க்கவும்",
    "marketplace.respond.step3": "விற்பனையாளருடன் தொடர்பு கொள்ளவும்:",
    "marketplace.respond.action1": "நேரடி செய்தி",
    "marketplace.respond.action2": "மின்னஞ்சல்",
    "marketplace.respond.action3": "தொலைபேசி (வழங்கப்பட்டால்)",
    "verification.title": "சரிபார்ப்பு",
    "verification.description": "உங்கள் கணக்கை சரிபார்க்கவும்",
    "verification.importance.title": "சரிபார்ப்பின் முக்கியத்துவம்",
    "verification.importance.description": "உங்கள் கணக்கை சரிபார்க்க வேண்டிய காரணங்கள்:",
    "verification.importance.reason1": "மற்ற பயனர்களுடன் நம்பிக்கையை உருவாக்குங்கள்",
    "verification.importance.reason2": "பிரீமியம் அம்சங்களுக்கு அணுகல் பெறுங்கள்",
    "verification.importance.reason3": "பாதுகாப்பான பரிவர்த்தனைகளை உறுதி செய்யுங்கள்",
    "verification.importance.reason4": "உங்கள் கணக்கை பாதுகாக்குங்கள்",
    "verification.steps.title": "சரிபார்ப்பு படிகள்",
    "verification.steps.description": "உங்கள் கணக்கை சரிபார்க்க இந்த படிகளைப் பின்பற்றவும்:",
    "verification.steps.step1": "உங்கள் சுயவிவர அமைப்புகளுக்குச் செல்லவும்",
    "verification.steps.step2": "'கணக்கை சரிபார்க்க' என்பதைக் கிளிக் செய்யவும்",
    "verification.steps.step3": "தேவையான ஆவணங்களை பதிவேற்றம் செய்யவும்:",
    "verification.steps.doc1": "அரசு அடையாள அட்டை",
    "verification.steps.doc2": "முகவரி சான்று",
    "verification.steps.doc3": "வணிக பதிவு (பொருந்துமானால்)",
    "verification.steps.step4": "சரிபார்ப்புக்காக சமர்ப்பிக்கவும்",
    "verification.steps.step5": "அங்கீகாரத்திற்காக காத்திருக்கவும் (பொதுவாக 1-2 வணிக நாட்கள்)",
  },
  hindi: {
    // ... existing code ...
    "contracts.title": "अनुबंध बनाना और प्रबंधित करना",
    "contracts.description": "कृषि अनुबंध बनाना, देखना और प्रबंधित करना सीखें",
    "contracts.create.title": "नया अनुबंध बनाना",
    "contracts.create.step1.title": "अनुबंध बनाने के लिए जाएं",
    "contracts.create.step1.description": 'अपने डैशबोर्ड से, साइडबार में "अनुबंध" पर क्लिक करें, फिर "नया अनुबंध बनाएं" चुनें।',
    "contracts.create.step2.title": "अनुबंध विवरण भरें",
    "contracts.create.step2.description": "अनुबंध फॉर्म में सभी आवश्यक फ़ील्ड भरें:",
    "contracts.create.step2.field1": "अनुबंध शीर्षक",
    "contracts.create.step2.field2": "अनुबंध प्रकार (निश्चित मूल्य, राजस्व साझाकरण, आदि)",
    "contracts.create.step2.field3": "प्रारंभ और समाप्ति तिथियां",
    "contracts.create.step2.field4": "फसल विवरण (प्रकार, मात्रा, गुणवत्ता मानक)",
    "contracts.create.step2.field5": "मूल्य जानकारी",
    "contracts.create.step2.field6": "भुगतान शर्तें",
    "contracts.create.step2.field7": "वितरण अनुसूची",
    "contracts.create.step3.title": "विशेष शर्तें जोड़ें (वैकल्पिक)",
    "contracts.create.step3.description": "अपने अनुबंध में कोई विशिष्ट विशेष शर्तें या शर्तें जोड़ें।",
    "contracts.create.step4.title": "समीक्षा करें और जमा करें",
    "contracts.create.step4.description": '"अनुबंध बनाएं" पर क्लिक करने से पहले सभी अनुबंध विवरणों की सावधानीपूर्वक समीक्षा करें।',
    "contracts.manage.title": "अनुबंध देखना और प्रबंधित करना",
    "contracts.manage.description": "अपने वर्तमान अनुबंधों को देखने के लिए:",
    "contracts.manage.step1": 'साइडबार में "अनुबंध" > "अनुबंध सूची" पर जाएं',
    "contracts.manage.step2": "स्थिति, तिथि या प्रकार के अनुसार अनुबंधों को क्रमबद्ध करने के लिए फ़िल्टर का उपयोग करें",
    "contracts.manage.step3": "विवरण देखने के लिए किसी भी अनुबंध पर क्लिक करें",
    "contracts.manage.step4": "अनुबंध विवरण पृष्ठ से, आप कर सकते हैं:",
    "contracts.manage.step4.action1": "अनुबंध दस्तावेज़ डाउनलोड करें",
    "contracts.manage.step4.action2": "अनुबंध समयरेखा और इतिहास देखें",
    "contracts.manage.step4.action3": "अनुबंध संपादित करें (यदि अनुमति दी गई है)",
    "contracts.manage.step4.action4": "अनुबंध समाप्त करें (यदि आवश्यक है)",

    "marketplace.title": "बाज़ार का उपयोग करना",
    "marketplace.description": "बाज़ार सूचियों को ब्राउज़ करना, बनाना और उनका जवाब देना सीखें",
    "marketplace.browse.title": "सूचियां ब्राउज़ करना",
    "marketplace.browse.description": "बाज़ार में कृषि उत्पाद और अनुबंध खोजें:",
    "marketplace.browse.step1": 'मुख्य नेविगेशन में "बाज़ार" पर क्लिक करें',
    "marketplace.browse.step2": "अपनी खोज को संकीर्ण करने के लिए फ़िल्टर का उपयोग करें:",
    "marketplace.browse.filter1": "उत्पाद प्रकार",
    "marketplace.browse.filter2": "स्थान",
    "marketplace.browse.filter3": "मूल्य सीमा",
    "marketplace.browse.filter4": "उपलब्धता तिथि",
    "marketplace.browse.step3": "पूर्ण विवरण देखने के लिए सूचियों पर क्लिक करें",
    "marketplace.create.title": "सूचियां बनाना",
    "marketplace.create.description": "अपने उत्पादों के लिए नई बाज़ार सूचियां बनाएं:",
    "marketplace.create.step1": 'बाज़ार में "सूची बनाएं" पर क्लिक करें',
    "marketplace.create.step2": "सूची विवरण भरें:",
    "marketplace.create.field1": "उत्पाद का नाम और विवरण",
    "marketplace.create.field2": "उपलब्ध मात्रा",
    "marketplace.create.field3": "प्रति इकाई मूल्य",
    "marketplace.create.field4": "स्थान",
    "marketplace.create.field5": "उपलब्ध तिथियां",
    "marketplace.create.field6": "गुणवत्ता विनिर्देश",
    "marketplace.create.field7": "छवियां (यदि लागू हो)",
    "marketplace.create.step3": "अपनी पसंदीदा संपर्क विधि सेट करें",
    "marketplace.create.step4": "अपनी सूची की समीक्षा करें और प्रकाशित करें",
    "marketplace.create.step5": "संभावित खरीदारों के प्रश्नों का उत्तर दें",
    "marketplace.respond.title": "सूचियों का जवाब देना",
    "marketplace.respond.description": "बाज़ार सूचियों के साथ बातचीत करें:",
    "marketplace.respond.step1": "सूची विवरण देखें",
    "marketplace.respond.step2": "उपलब्धता और मूल्य जांचें",
    "marketplace.respond.step3": "विक्रेता से संपर्क करें:",
    "marketplace.respond.action1": "सीधा संदेश",
    "marketplace.respond.action2": "ईमेल",
    "marketplace.respond.action3": "फ़ोन (यदि प्रदान किया गया है)",
    "verification.title": "सत्यापन",
    "verification.description": "अपने खाते की पुष्टि करें",
    "verification.importance.title": "सत्यापन का महत्व",
    "verification.importance.description": "आपको अपने खाते की पुष्टि क्यों करनी चाहिए:",
    "verification.importance.reason1": "अन्य उपयोगकर्ताओं के साथ विश्वास बनाएं",
    "verification.importance.reason2": "प्रीमियम सुविधाओं तक पहुंच प्राप्त करें",
    "verification.importance.reason3": "सुरक्षित लेनदेन सुनिश्चित करें",
    "verification.importance.reason4": "अपने खाते की सुरक्षा करें",
    "verification.steps.title": "सत्यापन के चरण",
    "verification.steps.description": "अपने खाते की पुष्टि करने के लिए इन चरणों का पालन करें:",
    "verification.steps.step1": "अपनी प्रोफ़ाइल सेटिंग्स पर जाएं",
    "verification.steps.step2": "'खाता सत्यापित करें' पर क्लिक करें",
    "verification.steps.step3": "आवश्यक दस्तावेज़ अपलोड करें:",
    "verification.steps.doc1": "सरकारी पहचान पत्र",
    "verification.steps.doc2": "पता प्रमाण",
    "verification.steps.doc3": "व्यवसाय पंजीकरण (यदि लागू हो)",
    "verification.steps.step4": "समीक्षा के लिए जमा करें",
    "verification.steps.step5": "स्वीकृति का इंतज़ार करें (आमतौर पर 1-2 व्यावसायिक दिन)",
  },
  telugu: {
    // ... existing code ...
    "contracts.title": "ఒప్పందాలను సృష్టించడం మరియు నిర్వహించడం",
    "contracts.description": "వ్యవసాయ ఒప్పందాలను సృష్టించడం, చూడటం మరియు నిర్వహించడం నేర్చుకోండి",
    "contracts.create.title": "కొత్త ఒప్పందాన్ని సృష్టించడం",
    "contracts.create.step1.title": "ఒప్పంద సృష్టికి వెళ్లండి",
    "contracts.create.step1.description": 'మీ డాష్‌బోర్డ్‌నుండి, సైడ్‌బార్‌లో "ఒప్పందాలు" క్లిక్ చేసి, "కొత్త ఒప్పందాన్ని సృష్టించు" ఎంచుకోండి.',
    "contracts.create.step2.title": "ఒప్పంద వివరాలను నింపండి",
    "contracts.create.step2.description": "ఒప్పంద ఫారమ్‌లో అవసరమైన అన్ని ఫీల్డ్‌లను నింపండి:",
    "contracts.create.step2.field1": "ఒప్పంద శీర్షిక",
    "contracts.create.step2.field2": "ఒప్పంద రకం (స్థిర ధర, ఆదాయ షేరింగ్, మొదలైనవి)",
    "contracts.create.step2.field3": "ప్రారంభ మరియు ముగింపు తేదీలు",
    "contracts.create.step2.field4": "పంట వివరాలు (రకం, పరిమాణం, నాణ్యత ప్రమాణాలు)",
    "contracts.create.step2.field5": "ధర సమాచారం",
    "contracts.create.step2.field6": "చెల్లింపు నిబంధనలు",
    "contracts.create.step2.field7": "అందింపు షెడ్యూల్",
    "contracts.create.step3.title": "ప్రత్యేక నిబంధనలు జోడించండి (ఐచ్ఛికం)",
    "contracts.create.step3.description": "మీ ఒప్పందానికి ఏదೆనೆ ప్రత్యేక నిబంధనలు లేదా షరతులను జోడించండి.",
    "contracts.create.step4.title": "సమీక్షించి సమర్పించండి",
    "contracts.create.step4.description": "\"ఒప్పందాన్ని సృష్టించు\" క్లిక్ చేసే ముందు అన్ని ఒప్పంద వివరాలను జాగ్రత్తగా సమీక్షించండి.",
    "contracts.manage.title": "ఒప్పందాలను చూడటం మరియు నిర్వహించడం",
    "contracts.manage.description": "మీ ప్రస్తుత ఒప్పందాలను చూడటానికి:",
    "contracts.manage.step1": 'సైడ്‌బార్‌లో "ఒప్పందాలు" > "ఒప్పంద జాబితా" కి వెళ్లండి',
    "contracts.manage.step2": "స్థితి, తేదీ లేదా రకం ద్వారా ఒప్పందాలను క్రమబద్ధీకరించడానికి ఫిల్టర్లను ఉపయోగించండి",
    "contracts.manage.step3": "వివరాలను చూడటానికి ఏదೆనೆ ఒప్పందాన్ని క్లిక్ చేయండి",
    "contracts.manage.step4": "ఒప్పంద వివరాల పేజీ నుండి, మీరు:",
    "contracts.manage.step4.action1": "ఒప్పంద పత్రాన్ని డౌన్‌లోడ్ చేయండి",
    "contracts.manage.step4.action2": "ఒప్పంద కాలక్రమం మరియు చరిత్రను చూడండి",
    "contracts.manage.step4.action3": "ఒప్పందాన్ని సవరించండి (అనుమతించబడితే)",
    "contracts.manage.step4.action4": "ఒప్పందాన్ని ముగించండి (అగత్యవిద్దరೆ)",

    "marketplace.title": "మార్కెట്‌ప్లేస్‌ని ఉపయೋగించడం",
    "marketplace.description": "మార్కెట്‌ప్లేస్ లిస్టింగ్స్‌ని బ్రౌజ్ చేయడం, సృష్టించడం మరియు వాటికి ప్రతిస్పందించడం నేర్చుకోండి",
    "marketplace.browse.title": "లిస్టింగ్స్‌ని బ్రౌజ్ చేయడం",
    "marketplace.browse.description": "మార్కెట്‌ప్లేస్‌లో వ్యవసాయ ఉత్పత్తులు మరియు ఒప్పందాలను కనుగొనండి:",
    "marketplace.browse.step1": 'ప్రధాన నావిగేషన్‌లో "మార్కെట്‌ప్లేస్" క్లిక్ చేయండి',
    "marketplace.browse.step2": "మీ శోధనను సంకుచితం చేయడానికి ఫిల్టర్లను ఉపయోగించండి:",
    "marketplace.browse.filter1": "ఉత్పత్తి రకం",
    "marketplace.browse.filter2": "స్థానం",
    "marketplace.browse.filter3": "ధర పరిధి",
    "marketplace.browse.filter4": "అందుబాటులో ఉన్న తేదీ",
    "marketplace.browse.step3": "పూర్తి వివరాలను చూడటానికి లిస్టింగ్స్‌ని క్లిక్ చేయండి",
    "marketplace.create.title": "లిస్టింగ్స్‌ని సృష్టించడం",
    "marketplace.create.description": "మీ ఉత్పత్తుల కోసం కొత్త మార్కెట്‌ప్లేస్ లిస్టింగ్స్‌ని సృష్టించండి:",
    "marketplace.create.step1": 'మార్కെట്‌ప్లేస్‌లో "లిస്టింగ് సృష్టించు" క్లిక్ చేయండి',
    "marketplace.create.step2": "లిస్టింగ్ వివరాలను నింపండి:",
    "marketplace.create.field1": "ఉత్పత్తి పేరు మరియు వివరణ",
    "marketplace.create.field2": "అందుబాటులో ఉన్న పరిమాణం",
    "marketplace.create.field3": "యూనిట్‌కి ధర",
    "marketplace.create.field4": "స్థానం",
    "marketplace.create.field5": "అందుబాటులో ఉన్న తేదీలు",
    "marketplace.create.field6": "నాణ్యత వివరఙ్ఙళ్‍",
    "marketplace.create.field7": "చిత్రాలు (అన్వయించబడితే)",
    "marketplace.create.step3": "మీ ప్రాధాన്య సంప్రదింపు విధానవన്നు హೊందిసి",
    "marketplace.create.step4": "మీ లిస్టింగ్‌ని సమీక్షించి ప్రచురించండి",
    "marketplace.create.step5": "సంభావ్య కొనുగോలుదారുల నుండి వచ്చే అభ్యర്థనలకు ప్రతిస్పందించండి",
    "marketplace.respond.title": "లిస్టింగ్స్‌కి ప్రతిస్పందించడం",
    "marketplace.respond.description": "మార్కെట്‌ప్లేస్ లిస్టింగ్స్‌తో ఇంటరాక్ట్ చేయండి:",
    "marketplace.respond.step1": "లిస్టింగ్ వివరాలను చూడండి",
    "marketplace.respond.step2": "అందుబాటు మరియు ధరలను తనిఖీ చేయండి",
    "marketplace.respond.step3": "విక്రేతతో సంప్రదించండి:",
    "marketplace.respond.action1": "నేరుగా సందేశం",
    "marketplace.respond.action2": "ఇమെయిల్",
    "marketplace.respond.action3": "ఫోన్ (అందించబడితే)",
    "verification.title": "ధృవీకరణ",
    "verification.description": "మీ ఖాతాను ధృవీకరించండి",
    "verification.importance.title": "ధృవీకరణ యొక്క ప్రాముఖ్యత",
    "verification.importance.description": "మీరు మీ ఖాతాను ధృవీకరించాల్సిన కారణాలు:",
    "verification.importance.reason1": "ఇతర వినియోగదారులు సాంబికిసి",
    "verification.importance.reason2": "ప్రీమియం లక్షణాలకు ప్రాప్యత పొందండి",
    "verification.importance.reason3": "సురక్షిత లావాదేవీలను నిర్ధారించండి",
    "verification.importance.reason4": "మీ ఖాతాను రక్షించండి",
    "verification.steps.title": "ధృవీకరణ దశలు",
    "verification.steps.description": "మీ ఖాతాను ధృవీకరించడానికి ఈ దశలను అనుసరించండి:",
    "verification.steps.step1": "మీ ప్రొఫൈల്‍ సെట್టింగ്స్‌గె హೋగి",
    "verification.steps.step2": "'ఖాతೆ పరిశీలిసి' క్లిక్ మాడి",
    "verification.steps.step3": "అగత్యవిరువ దాఖలೆగళన్ను అప്‌లోడ్ మాడి:",
    "verification.steps.doc1": "ప్రభുత്వ గుర్తిన దాఖలె",
    "verification.steps.doc2": "చిరునామా రుజువు",
    "verification.steps.doc3": "వ్యవసాయ నమോద് (అగత്యవిద്దరെ)",
    "verification.steps.step4": "సమీక్ష కోసం సల్లికె మాడి",
    "verification.steps.step5": "అనుమോదనೆగాగి కాయిరి (సామాన്యవాగి 1-2 వ్యవసాయిక దినగళు)",
  },
  kannada: {
    // ... existing code ...
    "contracts.title": "ಒಪ್ಪನ್ನು ಸೃಷ్ಟಿಸುವುದು ಮತ್ತು ನಿರ್ವಾಹಿಸುವುದು",
    "contracts.description": "ಕೃಷಿ ಒಪ್ಪನ್ನು ಸೃಷ్ಟಿಸುವುದು, ಅನುಸರಿಸುವುದು ಮತ್ತು ನಿರ್ವಾಹಿಸುವುದು",
    "contracts.create.title": "ಹೊಸ ಒಪ್ಪನ್ನು ಸೃಷ్ಟಿಸುವುದು",
    "contracts.create.step1.title": "ಒಪ್ಪನ್ನು ಸೃಷ్ಟಿಸುವುದು",
    "contracts.create.step1.description": 'ನಿಮ್ಮ ಡಾಷ್‌ಬೋರ್ಡ್‌ನుండి, ಸೈಡ్‌ಬಾರ್‌ಲೋ "ಒಪ್ಪನ್ನು" ಕ್ಲಿಕ్ ಮಾಡಿ, "ಹೊಸ ಒಪ್ಪನ್ನು ಸೃಷ్ಟಿಸು" ಎಂಚುವುದು.',
    "contracts.create.step2.title": "ಒಪ್ಪನ್ನು ವಿವರಗಳನు ನಿಲ್ಲಿಸಿ",
    "contracts.create.step2.description": "ಒಪ್ಪನ್ನು ಫಾರ್ಮ್‌ಲೋ ಅವಸರವಾದ ಅನ್ನಿ ಫೀಲ్ಡ್‌ಗಳನ್ನು ನಿಲ್ಲಿಸಿ:",
    "contracts.create.step2.field1": "ಒಪ್ಪನ್ನು ಶೀರ్ಷಿಕ",
    "contracts.create.step2.field2": "ಒಪ್ಪನ್ನು ರಕ",
    "contracts.create.step2.field3": "ಪ್ರಾರಂಭ ಮತ್ತು ಮುಚ್ಚಿಸುವ ದಿನಗಳು",
    "contracts.create.step2.field4": "ವಿವರ ವಿವರಗಳು (ರಕ, ಅಳತೆ, ಗುಣವತ್ತೆ ಮಾನಕ)",
    "contracts.create.step2.field5": "ಬೆಲೆ ಮಾಹಿತಿ",
    "contracts.create.step2.field6": "ಬಿಡುವಣಿಗಳು",
    "contracts.create.step2.field7": "ವಿತರಣ ಅನುಸರಣಿ",
    "contracts.create.step3.title": "ವಿಶೇಷ ಶರ್ತಗಳನ್ನು ಸೇರಿಸಿ (ಐಚ್ಛಿಕ)",
    "contracts.create.step3.description": "ನಿಮ್ಮ ಒಪ್ಪನ್ನು ಏದೆನೆ ವಿಶೇಷ ಶರ್ತಗಳು ಅಥವಾ ಶರ್ತಗಳನ್ನು ಸೇರಿಸಿ.",
    "contracts.create.step4.title": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸಮರ್ಪಿಸಿ",
    "contracts.create.step4.description": "\"ಒಪ್ಪನ್ನು ಸೃಷ್ಟಿಸು\" ಕ್ಲಿಕ് ಮುಂದೆ ಅನ್ನಿ ಒಪ್ಪನ್ನು ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "contracts.manage.title": "ಒಪ್ಪನ್ನು ಅನುಸರಿಸುವುದು ಮತ್ತು ನಿರ್ವಾಹಿಸುವುದು",
    "contracts.manage.description": "ನಿಮ್ಮ ಪ್ರಸ್తುತ ಒಪ್ಪನ್ನು ಅನುಸರಿಸಲು:",
    "contracts.manage.step1": 'ಸೈಡ്‌ಬಾರ್‌ಲೋ "ಒಪ್ಪನ್ನು" > "ಒಪ್ಪನ್ನು ಪಟ್ಟಿ" ಗೆ ಹೋಗಿ',
    "contracts.manage.step2": "ಸ್ಥಿತಿ, ದಿನಗಳು ಅಥವಾ ರಕದಿಂದ ಒಪ್ಪನ್ನು ಕ್ರಮಬದ್ಧಿಸಿದೆ",
    "contracts.manage.step3": "ವಿವರಗಳನ್ನು ಅನುಸರಿಸಲು ಏದೆನೆ ಒಪ್ಪನ್ನು ಕ್ಲಿಕ್ ಮಾಡಿ",
    "contracts.manage.step4": "ಒಪ್ಪನ್ನು ವಿವರಗಳ ಪೇಜ್ ನುಂಡಿ, ನಿಮ್ಮ:",
    "contracts.manage.step4.action1": "ಒಪ್ಪನ್ನು ಡೌನ్‌ಲೋಡ್ ಮಾಡಿ",
    "contracts.manage.step4.action2": "ಒಪ್ಪನ್ನು ಕಾಲಕ്ರಮ ಮತ್ತು ಇತಿಹಾಸ ಅನುಸರಿಸಿ",
    "contracts.manage.step4.action3": "ಒಪ್ಪನ್ನು ಸವರಿಸಿ (ಅನುಮತಿಸಿದಾಗ)",
    "contracts.manage.step4.action4": "ಒಪ್ಪನ್ನು ಮುಚ್ಚಿಸಿ (ಅಗತ್ಯವಿದ್ದರೆ)",

    "marketplace.title": "ಮಾರ്ಕെಟ്‌ಪ್ಲೇಸ್‌ನಿ ಉಪಯೋಗಿಸುವುದು",
    "marketplace.description": "ಮಾರ്ಕെಟ്‌ಪ್ಲೇಸ್ ಲಿಸ್ಟಿಂಗ್ಸ್‌ನಿ ಬ್ರೌಜ್ ಮಾಡಿ, ಸೃಷ്ಟಿಸುವುದು ಮತ್ತು ಅದರಲ್ಲಿ ಪ್ರತಿಸ್ಪಂದಿಸುವುದು",
    "marketplace.browse.title": "ಲಿಸ್ಟಿಂಗ്ಸ್‌ನಿ ಬ್ರೌಜ್ ಮಾಡಿ",
    "marketplace.browse.description": "ಮಾರ്ಕെಟ്‌ಪ್ಲೇಸ್‌ಲో ವ್ಯವಸಾಯ ಉತ್ಪತ్ತುಗಳು ಮತ್ತು ಒಪ್ಪನ್ನು ಕನ್ನಡಿಸಿ:",
    "marketplace.browse.step1": 'ಮುಖ്ಯ ನಾವಿಗೆಷನ್‌ಲೋ "ಮಾರ്ಕെಟ്‌ಪ್ಲೇಸ್" ಕ್ಲಿಕ్ ಮಾಡಿ',
    "marketplace.browse.step2": "ನಿಮ್ಮ ಶೋಧನನ్ನು ಸಂಕుಚಿತಂ ಮಾಡಲು ಫಿಲ್ಟರ್ಗಳನ್ನು ಉಪಯೋಗಿಸಿ:",
    "marketplace.browse.filter1": "ಉತ್ಪತ್ತಿ ರಕ",
    "marketplace.browse.filter2": "ಸ್ಥಳ",
    "marketplace.browse.filter3": "ಬೆಲೆ ವಿಸ್ತರ",
    "marketplace.browse.filter4": "ಅಂದುಬಾಟುಗಳಲ್ಲಿ ಇರುವ ದಿನ",
    "marketplace.browse.step3": "ಪೂರ్ತಿ ವಿವರಗಳನ్ನು ಅನುಸರಿಸಲು ಲಿಸ್ಟಿಂಗ്ಸ್‌ನಿ ಕ್ಲಿಕ్ ಮಾಡಿ",
    "marketplace.create.title": "ಲಿಸ್ಟಿಂಗ്ಸ್‌ನಿ ಸೃಷ്ಟಿಸುವುದು",
    "marketplace.create.description": "ನಿಮ್ಮ ಉತ್ಪತ್ತಗಳ ಕೋಸಂ ಹೊಸ ಮಾರ്ಕെಟ്‌ಪ್ಲೇಸ್ ಲಿಸ್ಟಿಂಗ്ಸ್‌ನಿ ಸೃಷ്ಟಿಸಿ:",
    "marketplace.create.step1": 'ಮಾರ്ಕെಟ്‌ಪ್ಲೇಸ್‌ಲೋ "ಲಿಸ್ಟಿಂಗ് ಸೃಷ്ಟಿಸು" ಕ್ಲಿಕ్ ಮಾಡಿ',
    "marketplace.create.step2": "ಲಿಸ್ಟಿಂಗ് ವಿವರಗಳನ್ನು ನಿಲ್ಲಿಸಿ:",
    "marketplace.create.field1": "ಉತ್ಪತ್ತಿ ಪೇರು ಮತ್ತು ವಿವರಣ",
    "marketplace.create.field2": "ಅಂದುಬಾಟುಗಳಲ್ಲಿ ಇರುವ ಅಳತೆ",
    "marketplace.create.field3": "ಯೂನಿಟ್‌ಕಿ ಬೆಲೆ",
    "marketplace.create.field4": "ಸ್ಥಳ",
    "marketplace.create.field5": "ಅಂದುಬಾಟುಗಳಲ್ಲಿ ಇರುವ ದಿನಗಳು",
    "marketplace.create.field6": "ನಾಣ್ಯತ ವಿವರಗಳು",
    "marketplace.create.field7": "ಚಿತ್ರಗಳು (ಅನ್ವಯಿಂಚಬಡಿತೇ)",
    "marketplace.create.step3": "ನಿಮ್ಮ ಪ್ರಾಧಾನ്ಯ ಸಂಪ್ರದಿಂಪು ವಿಧಾನವನ್ನು ಹೊಂದಿಸಿ",
    "marketplace.create.step4": "ನಿಮ್ಮ ಲಿಸ್ಟಿಂಗ്‌ನಿ ಪರಿಶೀಲಿಸಿ ಪ್ರಚುರಿಸಿ",
    "marketplace.create.step5": "ಸಂಭಾವ್ಯ ಕೊನುಗೋಲుದಾರുಲ ನುಂಡಿನು ವಚ്ಚೇ ಅಭ್ಯರ്ಥನಲು ಪ್ರತಿಸ್ಪಂದಿಸಿ",
    "marketplace.respond.title": "ಲಿಸ್ಟಿಂಗ്ಸ್‌ಕಿ ಪ್ರತಿಸ್ಪಂದಿಸಿ",
    "marketplace.respond.description": "ಮಾರ്ಕെಟ്‌ಪ್ಲೇಸ್ ಲಿಸ್ಟಿಂಗ്ಸ್‌ತೋ ಇಂಟರ್ಅಕ್ಟ್ ಮಾಡಿ:",
    "marketplace.respond.step1": "ಲಿಸ್ಟಿಂಗ് ವಿವರಗಳನ್ನು ಅನುಸರಿಸಿ",
    "marketplace.respond.step2": "ಅಂದುಬಾಟು ಮತ್ತು ಬೆಲೆಗಳನ್ನು ತನಿಖ್ಯಾಸಿ",
    "marketplace.respond.step3": "ವಿಕ്ರേತತೋ ಸಂಪ್ರದಿಸಿ:",
    "marketplace.respond.action1": "ನೇರుಗಾ ಸಂದೇಶಂ",
    "marketplace.respond.action2": "ಇಮെಯಿಲ్",
    "marketplace.respond.action3": "ಫೋನ್ (ಅಂದಿಸಿದಾಗ)",
    "verification.title": "ಧೃವೀಕರಣ",
    "verification.description": "ನಿಮ್ಮ ಖಾತಾನు ಧೃವೀಕರಿಸಿ",
    "verification.importance.title": "ಧೃವೀಕರಣ ಯೊಕ്ಕ ಪ್ರಾಮುಖ്ಯತ",
    "verification.importance.description": "ನಿಮ್ಮ ಖಾತಾನు ಧೃವೀಕರಿಸಲು ವೇಣಿಸಿದ ಕಾರಣಗಳು:",
    "verification.importance.reason1": "ಇತರ ವಿನಿಯೋಗದಾರుಲುಗಳು ಸಾಂಬಿಕಿಸಿ",
    "verification.importance.reason2": "ಪ್ರೀಮಿಯಂ ಲಕ್ಷಣಗಳು ಪ್ರಾಪ್ಯತ ಪೊಂದಿಸಿ",
    "verification.importance.reason3": "ಸುರಕ్ಷಿತ ಲಾವಾದಿವೆಲು ನಿರ್ಧಾರಿಂಚಂడి",
    "verification.importance.reason4": "ನಿಮ್ಮ ಖಾತಾನు ರಕ್ಷಿಸಿ",
    "verification.steps.title": "ಧೃವೀಕರಣ ದಶಲು",
    "verification.steps.description": "ನಿಮ್ಮ ಖಾತಾನు ಧೃವೀಕರಿಸಡಾನಿಕಿ ಈ ದಶಲು ಅನುಸರಿಸಿ:",
    "verification.steps.step1": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‍ ಸೆಟ್ಟಿಂಗ್ಸ್‌ಗೆ ಹೋಗಿ",
    "verification.steps.step2": "'ಖಾತೆ ಪರಿశీಲಿಸಿ' ಕ್ಲಿಕ్ ಮಾಡಿ",
    "verification.steps.step3": "ಅಗತ್ಯವಿರುವ ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ:",
    "verification.steps.doc1": "ಪ్ರಭുತ്ವ ಗుರ్ತಿನ ದಾಖಲೆ",
    "verification.steps.doc2": "ಚಿರುನಾಮಾ ರುಜುವು",
    "verification.steps.doc3": "ವ್ಯವಸಾಯ ನಮೋದ್ (ಅಗತ്ಯವಿದ്ದರെ)",
    "verification.steps.step4": "ಸಮಿಕ್ಷ ಕೋಸಂ ಸಲ್ಲಿಕೆ ಮಾಡಿ",
    "verification.steps.step5": "ಅನುಮോದನೆಗಾಗಿ ಕಾಯಿರಿ (ಸಾಮಾನ്ಯವಾಗಿ 1-2 ವ್ಯವಸಾಯಿಕ ದಿನಗಳు)",
  },
  malayalam: {
    // ... existing code ...
    "contracts.title": "ഒപ്പന്നുകളെ സൃഷ്ടിയോക്കുകയോക്കുക",
    "contracts.description": "കൃഷി ഒപ്പന്നുകളെ സൃഷ്ടിയോക്കുകയോക്കുക",
    "contracts.create.title": "പുതിയ ഒപ്പന്നുകളെ സൃഷ്ടിയോക്കുകയോക്കുക",
    "contracts.create.step1.title": "ഒപ്പന്നുകളെ സൃഷ്ടിയോക്കുകയോക്കുക",
    "contracts.create.step1.description": 'നിങ്ങളുടെ ഡാഷ്ബോറ്ഡ്നും, സൈഡ്ബാറ്റലോ "ഒപ്പന്നുകളെ" ക്ലിക്കുചേസുമ്പോൾ, "പുതിയ ഒപ്പന്നുകളെ" എന്ന് തിരഞ്ഞെടുക്കുക.',
    "contracts.create.step2.title": "ഒപ്പന്നുകളെ വിവരങ്ങളെ നിലപിടിക്കുക",
    "contracts.create.step2.description": "ഒപ്പന്നുകളെ ഫോറംലോ അവസരവാദ്ധീകളെ നിലപിടിക്കുക:",
    "contracts.create.step2.field1": "ഒപ്പന്നുകളെ ശീര്ഷിക",
    "contracts.create.step2.field2": "ഒപ്പന്നുകളെ രകം",
    "contracts.create.step2.field3": "പ്രാരംഭം മത്തുമ്പോളും മുടിയും ദിനങ്ങള്‍",
    "contracts.create.step2.field4": "പന്തയുടെ വിവരങ്ങള്‍ (രകം, അളവ്, ഗുണവത്താന്‍കള്‍)",
    "contracts.create.step2.field5": "വിലയുടെ വിവരങ്ങള്‍",
    "contracts.create.step2.field6": "പണമ്പിടുകയുടെ നിയമങ്ങള്‍",
    "contracts.create.step2.field7": "വിതരണ അനുസരണി",
    "contracts.create.step3.title": "പ്രത്യക്ഷവര്ത്തകളെ ചേര്തുകയോക്കുക (ഐച്ഛികം)",
    "contracts.create.step3.description": "നിങ്ങളുടെ ഒപ്പന്നുകളെ ഏതെന്നോ പ്രത്യക്ഷവര്ത്തകളെ അഥവാ ശരത്തുകളെ ചേര്തുകയോക്കുക.",
    "contracts.create.step4.title": "പരിശീലിക്കുക മത്തുമ്പോളും സമര്പിക്കുക",
    "contracts.create.step4.description": '"ഒപ്പന്നുകളെ സൃഷ്ടിയോക്കുക" ക്ലിക്കുചേസുമ്പോൾ അന്നോയിയിലുള്ള എല്ലാ ഒപ്പന്നുകളെ പരിശീലിക്കുക.',
    "contracts.manage.title": "ഒപ്പന്നുകളെ ചൂണ്ടിയോക്കുകയോക്കുക",
    "contracts.manage.description": "നിങ്ങളുടെ പ്രസ്തുത ഒപ്പന്നുകളെ ചൂണ്ടിയോക്കുകയോക്കുക:",
    "contracts.manage.step1": 'സൈഡ്ബാറ്റലോ "ഒപ്പന്നുകളെ" > "ഒപ്പന്നുകളുടെ പട്ടി" ഗെ ഹോഗി',
    "contracts.manage.step2": "സ്ഥിതി, ദിനം അഥവാ രകം ദ്വാരാ ഒപ്പന്നുകളെ ക്രമബദ്ധിസിദ്ദേശിക്കുക",
    "contracts.manage.step3": "വിവരങ്ങളെ ചൂണ്ടിയോക്കുകയോക്കുക",
    "contracts.manage.step4": "ഒപ്പന്നുകളെ വിവരങ്ങളുടെ പേജ് നും നിങ്ങളും:",
    "contracts.manage.step4.action1": "ഒപ്പന്നുകളെ ഡൗൺലോഡ് ചേയുക",
    "contracts.manage.step4.action2": "ഒപ്പന്നുകളെ കാലക്രമം മത്തും വരലാറ്റ് ചൂണ്ടിയോക്കുക",
    "contracts.manage.step4.action3": "ഒപ്പന്നുകളെ സവരിക്കുക (അനുമതിസിദ്ദായുണ്ടെങ്കിൽ)",
    "contracts.manage.step4.action4": "ഒപ്പന്നുകളെ മുടിയുകയോക്കുക (അഗത്യവിദ്ദരെങ്കിൽ)",

    "marketplace.title": "മാര്കെട്ട്പ്ലേസ്നി ഉപയോഗിക്കുക",
    "marketplace.description": "മാര്കെട്ട്പ്ലേസ് ലിസ്റ്റിംഗ്സ്നി ബ്രൌജ് ചേയുക, സൃഷ്ടിയോക്കുകയോക്കുകയോക്കുക",
    "marketplace.browse.title": "ലിസ്റ്റിംഗ്സ്നി ബ്രൌജ് ചേയുക",
    "marketplace.browse.description": "മാര്കെട്ട്പ്ലേസ്ലോ വിഷയയുടെ ഉത്പത്തകളും ഒപ്പന്നുകളെ കന്നഡിയോക്കുക:",
    "marketplace.browse.step1": 'മുഖ്യ നാവിഗേഷൻലോ "മാര്കെട്ട്പ്ലേസ്" ക്ലിക്കുചേസുമ്പോൾ',
    "marketplace.browse.step2": "നിങ്ങളുടെ ശോധനനു സംകుചിതം ചേയുകയോക്കുക:",
    "marketplace.browse.filter1": "ഉത്പത്തി രകം",
    "marketplace.browse.filter2": "സ്ഥാനം",
    "marketplace.browse.filter3": "വിലയുടെ പരിധി",
    "marketplace.browse.filter4": "അംദുബാടുകളല്ലി ഇരുന്ന ദിനം",
    "marketplace.browse.step3": "പൂര్ത്തി വിവരങ്ങളെ ചൂണ്ടിയോക്കുക ലിസ്റ്റിംഗ്സ്നി ക്ലിക്കുചേസുമ്പോൾ",
    "marketplace.create.title": "ലിസ്റ്റിംഗ്സ്നി സൃഷ്ടിയോക്കുക",
    "marketplace.create.description": "നിങ്ങളുടെ ഉത്പത്തകളുകൾക്ക് പുതിയ മാര്കെട്ട്പ്ലേസ് ലിസ്റ്റിംഗ്സ്നി സൃഷ്ടിയോക്കുക:",
    "marketplace.create.step1": 'മാര്കെട്ട്പ്ലേസ്ലോ "ലിസ്റ്റിംഗ് സൃഷ്ടിയോക്കുക" ക്ലിക്കുചേസുമ്പോൾ',
    "marketplace.create.step2": "ലിസ്റ്റിംഗ് വിവരങ്ങളെ നിലപിടിക്കുക:",
    "marketplace.create.field1": "ഉത്പത്തി പേരെ വിവരണം",
    "marketplace.create.field2": "അംദുബാടുകളല്ലി ഇരുന്ന അളവ്",
    "marketplace.create.field3": "യൂനിറ്റ്കി വില",
    "marketplace.create.field4": "സ്ഥാനം",
    "marketplace.create.field5": "അംദുബാടുകളല്ലി ഇരുന്ന ദിനങ്ങള്‍",
    "marketplace.create.field6": "നാണ്യത വിവരങ്ങള്‍",
    "marketplace.create.field7": "ചിത്രങ്ങള്‍ (അന്വയിംചബഡിതേ)",
    "marketplace.create.step3": "നിങ്ങളുടെ പ്രാധാന്യ സംപ്രദിംപു വിധാനവന്നു ഹൊക്കുസ്സു",
    "marketplace.create.step4": "നിങ്ങളുടെ ലിസ്റ്റിംഗ്സ്നി പരിശീലിക്കുക മത്തും പ്രചുരിക്കുക",
    "marketplace.create.step5": "സംഭാവ్യ കൊനുഗോലుദാരുലോടെ വച്ചേ അഭയര്ഥനലുകളും പ്രതിസ്പംദിക്കുക",
    "marketplace.respond.title": "ലിസ്റ്റിംഗ്സ്നി പ്രതിസ്പംദിക്കുക",
    "marketplace.respond.description": "മാര്കെട്ട്പ്ലേസ് ലിസ്റ്റിംഗ്സ്നിതോ ഇംടറാക്ട് ചേയുക:",
    "marketplace.respond.step1": "ലിസ്റ്റിംഗ്സ്നി വിവരങ്ങളെ ചൂണ്ടിയോക്കുക",
    "marketplace.respond.step2": "അംദുബാടുകളനും വിലങ്ങളും തനിഖ്യാസിക്കുക",
    "marketplace.respond.step3": "വിക്രേതാതോ സംപ്രദിക്കുക:",
    "marketplace.respond.action1": "നേരుഗാ സംദേശം",
    "marketplace.respond.action2": "ഇമെയില്",
    "marketplace.respond.action3": "ഫോണ് (അംദിസിയുണ്ടെങ്കിൽ)",
    "verification.title": "ധൃവീകരണം",
    "verification.description": "നിങ്ങളുടെ ഖാതാനు ധൃവീകരിക്കുക",
    "verification.importance.title": "ധൃവീകരണം യൊക്ക പ്രാമുഖ്യത",
    "verification.importance.description": "നിങ്ങളുടെ ഖാതാനు ധൃവീകരിക്കാനുള്ള കാരണങ്ങള്‍:",
    "verification.importance.reason1": "ഇതര വിനിയోഗദാരుകളുടെയും നമ്പിക്കയുടെയും",
    "verification.importance.reason2": "പ്രീമിയം അമ്ചങ്ങളുകൾക്ക് അണുക്കുക",
    "verification.importance.reason3": "സുരക്ഷിത ലാവാദിവെലുകളും നിര്ധാരിക്കുക",
    "verification.importance.reason4": "നിങ്ങളുടെ ഖാതാനు രക്ഷിക്കുക",
    "verification.steps.title": "ധൃവീകരണം ദശലുകൾ",
    "verification.steps.description": "നിങ്ങളുടെ ഖാതാനు ധൃവീകരിക്കാനുള്ള ഈ ദശലുകൾ അനുസരിക്കുക:",
    "verification.steps.step1": "നിങ്ങളുടെ പ്രൊഫൈല്‍ സെറ്റിംഗ്സ്നി ഹോഗി",
    "verification.steps.step2": "'ഖാതೆ പരിశీലിസി' ക്ലിക്കുചേസുമ്പോൾ",
    "verification.steps.step3": "അഗത്യവിരുവ ദാഖലെഗളന്നു അപ്‌ലോഡ്മാഡി:",
    "verification.steps.doc1": "പ്രഭുത്വ ഗുര്തിന ദാഖലെ",
    "verification.steps.doc2": "ചിരുനാമാ രുജുവു",
    "verification.steps.doc3": "വിവാര നമോദ് (അഗത്യവിദ്ദരെ)",
    "verification.steps.step4": "സമിക്ഷയുടെയും സല్ലികെയും മാഡി",
    "verification.steps.step5": "അനുമോദനയുടെയും കായിരിയും (സാമാന്യവാഗി 1-2 വിവാര ദിനങ്ങള్‍)",
  },
} as const

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("english")

  const t = (key: TranslationKey): string => {
    if (!(key in translations.english)) {
      console.warn(`Translation key "${key}" does not exist in English translations`)
      return key
    }

    const translation = translations[language][key]
    if (!translation) {
      console.warn(`Translation missing for key: ${key} in language: ${language}`)
      return translations.english[key] || key
    }
    return translation
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
} 