"use client"

import React, { createContext, useContext, useState } from "react"

export type Language = "english" | "tamil" | "hindi" | "telugu" | "kannada" | "malayalam"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Basic translations object - you can expand this
const translations = {
  english: {
    "guide.title": "User Guide",
    "guide.welcome": "Welcome to our comprehensive user guide. Learn how to use all features of our platform.",
    "tab.signup": "Sign Up",
    "tab.login": "Login",
    "tab.contracts": "Contracts",
    "tab.marketplace": "Marketplace",
    "tab.negotiation": "Negotiation",
    "tab.transactions": "Transactions",
    "tab.profile": "Profile",
    "tab.verification": "Verification",
    "guide.next": "Next",
    "language.english": "English",
    "language.tamil": "Tamil",
    "language.hindi": "Hindi",
    "language.telugu": "Telugu",
    "language.kannada": "Kannada",
    "language.malayalam": "Malayalam",
    "Select Language": "Select Language",
    "signup.title": "Creating an Account",
    "signup.description": "Follow these steps to create your agricultural contract account",
    "signup.step1.title": "Step 1: Go to Sign Up Page",
    "signup.step1.description": 'Click the "Sign Up" button in the website\'s top navigation bar.',
    "signup.step1.tip": "You can directly access the signup page",
    "signup.step2.title": "Step 2: Fill in Your Personal Information",
    "signup.step2.description": "Fill in all required fields in the signup form:",
    "signup.step2.field1": "Full Name (as it appears in your official documents)",
    "signup.step2.field2": "Email Address (you will need to verify this later)",
    "signup.step2.field3": "Phone Number (with country code)",
    "signup.step2.field4": "Password (at least 8 characters, mix of letters, numbers, and symbols)",
    "signup.step2.field5": "Address (your primary business or residence address)",
    "signup.step3.title": "Step 3: Choose Your User Role",
    "signup.step3.description": "Select the role that best describes you:",
    "signup.step3.role1.title": "Farmer",
    "signup.step3.role1.description": "If you want to grow and sell crops or enter into agricultural contracts",
    "signup.step3.role2.title": "Buyer",
    "signup.step3.role2.description": "If you buy agricultural products from farmers",
    "signup.step3.role3.title": "Agent",
    "signup.step3.role3.description": "If you facilitate transactions between farmers and buyers",
    "signup.step4.title": "Step 4: Create Your Account",
    "signup.step4.description": 'Click the "Create Account" button to submit your information. You will be redirected to the verification page.',
    "login.title": "Logging into Your Account",
    "login.description": "Access your agricultural contract dashboard by logging in",
    "login.step1.title": "Step 1: Go to Login Page",
    "login.step1.description": 'Click the "Login" button in the website\'s top navigation bar.',
    "login.step2.title": "Step 2: Enter Your Credentials",
    "login.step2.description": "Enter your registered email address and password in the respective fields.",
    "login.step2.tip": 'If you forgot your password, click the "Forgot Password?" link to reset it.',
    "login.step3.title": "Step 3: Access Your Dashboard",
    "login.step3.description": "After successfully logging in, you will be redirected to your personalized dashboard based on your user role.",
    // Add more translations as needed
  },
  tamil: {
    "guide.title": "பயனர் வழிகாட்டி",
    "guide.welcome": "எங்கள் விரிவான பயனர் வழிகாட்டிக்கு வரவேற்கிறோம். எங்கள் தளத்தின் அனைத்து அம்சங்களையும் பயன்படுத்த கற்றுக்கொள்ளுங்கள்.",
    "tab.signup": "பதிவு செய்க",
    "tab.login": "உள்நுழைக",
    "tab.contracts": "ஒப்பந்தங்கள்",
    "tab.marketplace": "சந்தை",
    "tab.negotiation": "பேச்சுவார்த்தை",
    "tab.transactions": "பரிவர்த்தனைகள்",
    "tab.profile": "சுயவிவரம்",
    "tab.verification": "சரிபார்ப்பு",
    "guide.next": "அடுத்து",
    "language.english": "ஆங்கிலம்",
    "language.tamil": "தமிழ்",
    "language.hindi": "இந்தி",
    "language.telugu": "தெலுங்கு",
    "language.kannada": "கன்னடம்",
    "language.malayalam": "மலையாளம்",
    "Select Language": "மொழியைத் தேர்ந்தெடுக்கவும்",
    "signup.title": "கணக்கை உருவாக்குதல்",
    "signup.description": "உங்கள் விவசாய ஒப்பந்த கணக்கை உருவாக்க இந்த படிகளைப் பின்பற்றவும்",
    "signup.step1.title": "படி 1: பதிவு செய்யும் பக்கத்திற்குச் செல்லவும்",
    "signup.step1.description": 'வலைத்தளத்தின் மேல் வழிசெலுத்தல் பட்டியில் உள்ள "பதிவு செய்க" பொத்தானைக் கிளிக் செய்யவும்.',
    "signup.step1.tip": "நீங்கள் நேரடியாக பதிவு பக்கத்தை அணுகலாம்",
    "signup.step2.title": "படி 2: உங்கள் தனிப்பட்ட தகவலை நிரப்பவும்",
    "signup.step2.description": "பதிவு படிவத்தில் தேவையான அனைத்து புலங்களையும் நிரப்பவும்:",
    "signup.step2.field1": "முழு பெயர் (உங்கள் அதிகாரப்பூர்வ ஆவணங்களில் தோன்றும் பெயர்)",
    "signup.step2.field2": "மின்னஞ்சல் முகவரி (நீங்கள் பின்னர் இதை சரிபார்க்க வேண்டும்)",
    "signup.step2.field3": "தொலைபேசி எண் (நாட்டு குறியீட்டுடன்)",
    "signup.step2.field4": "கடவுச்சொல் (எழுத்துகள், எண்கள் மற்றும் சின்னங்களின் கலவையுடன் குறைந்தது 8 எழுத்துகள் இருக்க வேண்டும்)",
    "signup.step2.field5": "முகவரி (உங்கள் முதன்மை வணிகம் அல்லது வசிப்பிட முகவரி)",
    "signup.step3.title": "படி 3: உங்கள் பயனர் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்",
    "signup.step3.description": "உங்களை சிறப்பாக விவரிக்கும் பொருத்தமான பாத்திரத்தைத் தேர்ந்தெடுக்கவும்:",
    "signup.step3.role1.title": "விவசாயி",
    "signup.step3.role1.description": "நீங்கள் பயிர்களை வளர்த்து அவற்றை விற்க விரும்பினால் அல்லது விவசாய ஒப்பந்தங்களில் நுழைய விரும்பினால்",
    "signup.step3.role2.title": "வாங்குபவர்",
    "signup.step3.role2.description": "நீங்கள் விவசாயிகளிடமிருந்து விவசாய பொருட்களை வாங்கினால்",
    "signup.step3.role3.title": "ஏஜென்ட்",
    "signup.step3.role3.description": "நீங்கள் விவசாயிகளுக்கும் வாங்குபவர்களுக்கும் இடையே பரிவர்த்தனைகளை எளிதாக்கினால்",
    "signup.step4.title": "படி 4: உங்கள் கணக்கை உருவாக்கவும்",
    "signup.step4.description": 'உங்கள் தகவலைச் சமர்ப்பிக்க "கணக்கை உருவாக்கு" பொத்தானைக் கிளிக் செய்யவும். நீங்கள் சரிபார்ப்பு பக்கத்திற்கு வழிநடத்தப்படுவீர்கள்.',
    "login.title": "உங்கள் கணக்கில் உள்நுழைதல்",
    "login.description": "உள்நுழைவதன் மூலம் உங்கள் விவசாய ஒப்பந்த டாஷ்போர்டை அணுகவும்",
    "login.step1.title": "படி 1: உள்நுழைவு பக்கத்திற்குச் செல்லவும்",
    "login.step1.description": 'வலைத்தளத்தின் மேல் வழிசெலுத்தல் பட்டியில் உள்ள "உள்நுழைக" பொத்தானைக் கிளிக் செய்யவும்.',
    "login.step2.title": "படி 2: உங்கள் சான்றுகளை உள்ளிடவும்",
    "login.step2.description": "உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சல் முகவரி மற்றும் கடவுச்சொல்லை அந்தந்த புலங்களில் உள்ளிடவும்.",
    "login.step2.tip": 'உங்கள் கடவுச்சொல்லை மறந்துவிட்டால், அதை மீட்டமைக்க "கடவுச்சொல் மறந்துவிட்டீர்களா?" இணைப்பைக் கிளிக் செய்யவும்.',
    "login.step3.title": "படி 3: உங்கள் டாஷ்போர்டை அணுகவும்",
    "login.step3.description": "வெற்றிகரமாக உள்நுழைந்த பிறகு, உங்கள் பயனர் பாத்திரத்தின் அடிப்படையில் உங்கள் தனிப்பயனாக்கப்பட்ட டாஷ்போர்டுக்கு நீங்கள் வழிநடத்தப்படுவீர்கள்.",
    "contracts.title": "ஒப்பந்தங்கள்",
    "contracts.description": "ஒப்பந்தங்களை உருவாக்கவும் மற்றும் நிர்வகிக்கவும்",
    "contracts.create.title": "ஒப்பந்தத்தை உருவாக்குதல்",
    "contracts.create.description": "புதிய விவசாய ஒப்பந்தத்தை உருவாக்க இந்த படிகளைப் பின்பற்றவும்",
    "contracts.create.step1.title": "படி 1: ஒப்பந்த விவரங்களை உள்ளிடவும்",
    "contracts.create.step1.description": "ஒப்பந்தத்தின் அடிப்படை தகவல்களை உள்ளிடவும்",
    "contracts.create.step2.title": "படி 2: ஒப்பந்த விவரங்களை உள்ளிடவும்",
    "contracts.create.step2.description": "ஒப்பந்தத்தின் விரிவான தகவல்களை உள்ளிடவும்",
    "contracts.create.step2.field1": "ஒப்பந்தத்தின் பெயர்",
    "contracts.create.step2.field2": "ஒப்பந்த வகை",
    "contracts.create.step2.field3": "தொடக்க மற்றும் முடிவு தேதிகள்",
    "contracts.create.step2.field4": "பயிர் விவரங்கள் (வகை, அளவு, தர தரநிலைகள்)",
    "contracts.create.step2.field5": "விலை விவரங்கள்",
    "contracts.create.step2.field6": "பணம் செலுத்தும் விதிமுறைகள்",
    "contracts.create.step2.field7": "விநியோக அட்டவணை",
    "contracts.create.step3.title": "சிறப்பு விதிமுறைகளை சேர்க்கவும் (விருப்பத்தேர்வு)",
    "contracts.create.step3.description": "உங்கள் ஒப்பந்தத்திற்கு எந்தவொரு சிறப்பு விதிமுறைகள் அல்லது நிபந்தனைகளை சேர்க்கவும்",
    "contracts.create.step4.title": "மதிப்பாய்வு செய்து சமர்ப்பிக்கவும்",
    "contracts.create.step4.description": "ஒப்பந்தத்தை உருவாக்கவும்",
    "contracts.manage.title": "ஒப்பந்தங்களை நிர்வகித்தல்",
    "contracts.manage.description": "உங்கள் ஒப்பந்தங்களை பார்வையிடவும் மற்றும் நிர்வகிக்கவும்",
    "contracts.manage.step1": "ஒப்பந்தங்கள் பக்கத்திற்குச் செல்லவும்",
    "contracts.manage.step2": "ஒப்பந்தங்களின் பட்டியலைப் பார்வையிடவும்",
    "contracts.manage.step3": "எந்தவொரு ஒப்பந்தத்தையும் கிளிக் செய்து அதன் விவரங்களைப் பார்வையிடவும்",
    "contracts.manage.step4": "ஒப்பந்த விவரங்கள் பக்கத்திலிருந்து, நீங்கள்:",
    "contracts.manage.step4.action1": "ஒப்பந்த ஆவணத்தை பதிவிறக்கவும்",
    "contracts.manage.step4.action2": "ஒப்பந்த காலவரிசை மற்றும் வரலாற்றைப் பார்வையிடவும்",
    "contracts.manage.step4.action3": "ஒப்பந்தத்தை திருத்தவும் (அனுமதிக்கப்பட்டால்)",
    "contracts.manage.step4.action4": "ஒப்பந்தத்தை முடிக்கவும் (தேவைப்பட்டால்)",

    "marketplace.title": "சந்தையைப் பயன்படுத்துதல்",
    "marketplace.description": "சந்தை பட்டியல்களை உலாவவும், உருவாக்கவும் மற்றும் பதிலளிக்கவும் கற்றுக்கொள்ளுங்கள்",
    "marketplace.browse.title": "பட்டியல்களை உலாவுதல்",
    "marketplace.browse.description": "சந்தையில் விவசாய பொருட்கள் மற்றும் ஒப்பந்தங்களைக் கண்டறியவும்:",
    "marketplace.browse.step1": "முக்கிய வழிசெலுத்தலில் 'சந்தை'க்குச் செல்லவும்",
    "marketplace.browse.step2": "உங்கள் தேடலை குறைக்க வடிகட்டிகளைப் பயன்படுத்தவும்:",
    "marketplace.browse.filter1": "பொருள் வகை",
    "marketplace.browse.filter2": "இருப்பிடம்",
    "marketplace.browse.filter3": "விலை வரம்பு",
    "marketplace.browse.filter4": "கிடைக்கும் தேதி",
    "marketplace.browse.step3": "முழு விவரங்களைப் பார்வையிட பட்டியல்களைக் கிளிக் செய்யவும்",
    "marketplace.create.title": "பட்டியல்களை உருவாக்குதல்",
    "marketplace.create.description": "உங்கள் பொருட்களுக்கான புதிய சந்தை பட்டியல்களை உருவாக்கவும்:",
    "marketplace.create.step1": "சந்தையில் 'பட்டியல் உருவாக்கு' என்பதைக் கிளிக் செய்யவும்",
    "marketplace.create.step2": "பட்டியல் விவரங்களை நிரப்பவும்:",
    "marketplace.create.field1": "பொருள் பெயர் மற்றும் விளக்கம்",
    "marketplace.create.field2": "கிடைக்கும் அளவு",
    "marketplace.create.field3": "ஒரு அலகுக்கான விலை",
    "marketplace.create.field4": "இருப்பிடம்",
    "marketplace.create.field5": "கிடைக்கும் தேதிகள்",
    "marketplace.create.field6": "தர விவரக்குறிப்புகள்",
    "marketplace.create.field7": "படங்கள் (பொருந்துமானால்)",
    "marketplace.create.step3": "உங்கள் விருப்பமான தொடர்பு முறையை அமைக்கவும்",
    "marketplace.create.step4": "உங்கள் பட்டியலை மதிப்பாய்வு செய்து வெளியிடவும்",
    "marketplace.create.step5": "உங்கள் பட்டியலை வெளியிடவும்",

    "negotiation.title": "பேச்சுவார்த்தை",
    "negotiation.description": "பேச்சுவார்த்தை மற்றும் ஒப்பந்தங்களை முடிக்கவும்",
    "negotiation.start.title": "பேச்சுவார்த்தையைத் தொடங்குதல்",
    "negotiation.start.description": "பேச்சுவார்த்தைத் தொடங்க இந்த படிகளைப் பின்பற்றவும்",
    "negotiation.start.step1": "சந்தை பட்டியலைத் தேர்ந்தெடுக்கவும்",
    "negotiation.start.step2": "பேச்சுவார்த்தைத் தொடங்க 'பேச்சுவார்த்தை' பொத்தானைக் கிளிக் செய்யவும்",
    "negotiation.start.step3": "பேச்சுவார்த்தை விவரங்களை உள்ளிடவும்:",
    "negotiation.start.field1": "விலை முன்மொழிவு",
    "negotiation.start.field2": "விநியோக தேதி",
    "negotiation.start.field3": "பேச்சுவார்த்தை குறிப்பு",
    "negotiation.start.field4": "பிற தேவைகள்",
    "negotiation.start.step4": "பேச்சுவார்த்தைத் தொடங்க 'அனுப்பு' பொத்தானைக் கிளிக் செய்யவும்",
    "negotiation.start.step5": "பேச்சுவார்த்தை நிலையைக் கண்காணிக்கவும்",

    "transactions.title": "பரிவர்த்தனைகள்",
    "transactions.description": "பரிவர்த்தனைகளை பார்வையிடவும் மற்றும் நிர்வகிக்கவும்",
    "transactions.view.title": "பரிவர்த்தனைகளைப் பார்வையிடுதல்",
    "transactions.view.description": "உங்கள் பரிவர்த்தனைகளைப் பார்வையிடவும்",
    "transactions.view.step1": "பரிவர்த்தனைகள் பக்கத்திற்குச் செல்லவும்",
    "transactions.view.step2": "பரிவர்த்தனைகளை வடிகட்டவும்:",
    "transactions.view.filter1": "தேதி வரம்பு",
    "transactions.view.filter2": "பரிவர்த்தனை வகை",
    "transactions.view.filter3": "நிலை",
    "transactions.view.step3": "பரிவர்த்தனைகளை வரிசைப்படுத்தவும்:",
    "transactions.view.sort1": "தேதி",
    "transactions.view.sort2": "தொகை",
    "transactions.view.sort3": "நிலை",

    "profile.title": "சுயவிவரம்",
    "profile.description": "உங்கள் கணக்கு விவரங்களை நிர்வகிக்கவும்",
    "profile.access.title": "சுயவிவரத்தை அணுகுதல்",
    "profile.access.description": "உங்கள் சுயவிவரத்தை அணுக இந்த படிகளைப் பின்பற்றவும்",
    "profile.access.step1": "மேல் வழிசெலுத்தல் பட்டியில் உங்கள் பெயரைக் கிளிக் செய்யவும்",
    "profile.access.step2": "கைவிரல் மெனு இருந்து 'சுயவிவரம்' என்பதைத் தேர்ந்தெடுக்கவும்",
    "profile.access.step3": "உங்கள் சுயவிவர பக்கத்தைப் பார்வையிடவும்",

    "verification.title": "சரிபார்ப்பு",
    "verification.description": "உங்கள் கணக்கை சரிபார்க்கவும்",
    "verification.importance.title": "சரிபார்ப்பின் முக்கியத்துவம்",
    "verification.importance.description": "உங்கள் கணக்கை சரிபார்க்க வேண்டிய காரணங்கள்:",
    "verification.importance.reason1": "பாதுகாப்பான பரிவர்த்தனைகள்",
    "verification.importance.reason2": "நம்பகமான வணிக உறவுகள்",
    "verification.importance.reason3": "முழு அணுகல் அம்சங்கள்",
    "verification.importance.reason4": "சட்டப்பூர்வ பாதுகாப்பு",
    "verification.document.title": "ஆவண சரிபார்ப்பு",
    "verification.document.description": "உங்கள் கணக்கை சரிபார்க்க ஆவணங்களை சமர்ப்பிக்கவும்",
    "verification.document.step1": "சரிபார்ப்பு பக்கத்திற்குச் செல்லவும்",
    "verification.document.step2": "தேவையான ஆவணங்களைத் தேர்ந்தெடுக்கவும்",
    "verification.document.step3": "பின்வரும் ஆவணங்களை சமர்ப்பிக்கவும்:",
    "verification.document.doc1": "அடையாள சான்று",
    "verification.document.doc2": "முகவரி சான்று",
    "verification.document.doc3": "வங்கி விவரங்கள்",
    "verification.document.step4": "ஆவணங்கள் பின்வரும் தேவைகளை பூர்த்தி செய்ய வேண்டும்:",
    "verification.document.req1": "தெளிவான மற்றும் படிக்கக்கூடிய",
    "verification.document.req2": "சமீபத்திய தேதியுடன்",
    "verification.document.req3": "சட்டப்பூர்வமாக செல்லுபடியாகும்",
    "verification.document.step5": "ஆவணங்களை பதிவேற்றம் செய்யவும்",
    "verification.identity.title": "அடையாள சரிபார்ப்பு",
    "verification.identity.description": "உங்கள் அடையாளத்தை சரிபார்க்கவும்",
    "verification.identity.step1": "உங்கள் அடையாள சான்றைத் தேர்ந்தெடுக்கவும்",
    "verification.identity.step2": "உங்கள் அடையாள சான்றின் படத்தை பதிவேற்றம் செய்யவும்",
    "verification.identity.step3": "பின்வரும் அடையாள சான்றுகளில் ஒன்றை சமர்ப்பிக்கவும்:",
    "verification.identity.id1": "ஆதார் அட்டை",
    "verification.identity.id2": "பான் அட்டை",
    "verification.identity.id3": "வாக்காளர் அடையாள அட்டை",
    "verification.identity.step4": "சரிபார்ப்பு நிலையைக் கண்காணிக்கவும்",
    "verification.identity.privacy": "உங்கள் ஆவணங்கள் பாதுகாப்பாக வைக்கப்படும் மற்றும் மறைமுகமாக கையாளப்படும்",
    "verification.status.title": "சரிபார்ப்பு நிலை",
    "verification.status.description": "உங்கள் சரிபார்ப்பு நிலையைக் கண்காணிக்கவும்",
    "verification.status.step1": "சரிபார்ப்பு பக்கத்திற்குச் செல்லவும்",
    "verification.status.step2": "சரிபார்ப்பு நிலையைப் பார்வையிடவும்",
    "verification.status.step3": "தேவைப்பட்டால் கூடுதல் ஆவணங்களை சமர்ப்பிக்கவும்",
    "verification.status.step4": "சரிபார்ப்பு முடிவைக் காத்திருக்கவும்",
    "verification.levels.title": "சரிபார்ப்பு நிலைகள்",
    "verification.levels.description": "பல்வேறு சரிபார்ப்பு நிலைகள் மற்றும் அவற்றின் நன்மைகள்:",
    "verification.levels.level1.title": "அடிப்படை சரிபார்ப்பு",
    "verification.levels.level1.description": "அடையாள சான்று மற்றும் முகவரி சான்று",
    "verification.levels.level2.title": "மேம்படுத்தப்பட்ட சரிபார்ப்பு",
    "verification.levels.level2.description": "வங்கி விவரங்கள் மற்றும் வணிக ஆவணங்கள்",
    "verification.levels.level3.title": "முழு சரிபார்ப்பு",
    "verification.levels.level3.description": "அனைத்து ஆவணங்கள் மற்றும் கூடுதல் சரிபார்ப்புகள்",
    "verification.levels.tip": "உயர் சரிபார்ப்பு நிலைகள் அதிக நம்பகத்தன்மை மற்றும் அணுகலை வழங்கும்"
  },
  hindi: {
    "guide.title": "उपयोगकर्ता मार्गदर्शिका",
    "guide.welcome": "हमारे व्यापक उपयोगकर्ता मार्गदर्शिका में आपका स्वागत है। हमारे प्लेटफॉर्म की सभी सुविधाओं का उपयोग करना सीखें।",
    "tab.signup": "साइन अप",
    "tab.login": "लॉग इन",
    "tab.contracts": "अनुबंध",
    "tab.marketplace": "बाज़ार",
    "tab.negotiation": "बातचीत",
    "tab.transactions": "लेनदेन",
    "tab.profile": "प्रोफ़ाइल",
    "tab.verification": "सत्यापन",
    "guide.next": "अगला",
    "language.english": "अंग्रे़ी",
    "language.tamil": "तमिल",
    "language.hindi": "हिंदी",
    "language.telugu": "तेलुगु",
    "language.kannada": "कन्नड़",
    "language.malayalam": "मलयालम",
    "Select Language": "भाषा चुनें",
    "signup.title": "खाता बनाना",
    "signup.description": "अपना कृषि अनुबंध खाता बनाने के लिए इन चरणों का पालन करें",
    "signup.step1.title": "चरण 1: साइन अप पेज पर जाएं",
    "signup.step1.description": 'वेबसाइट के शीर्ष नेविगेशन बार में "साइन अप" बटन पर क्लिक करें।',
    "signup.step1.tip": "आप सीधे साइन अप पेज तक पहुंच सकते हैं",
    "signup.step2.title": "चरण 2: अपनी व्यक्तिगत जानकारी भरें",
    "signup.step2.description": "साइन अप फॉर्म में सभी आवश्यक फ़ील्ड भरें:",
    "signup.step2.field1": "पूरा नाम (जैसा आपके आधिकारिक दस्तावेज़ों में दिखाई देता है)",
    "signup.step2.field2": "ईमेल पता (जिसे आप बाद में सत्यापित करेंगे)",
    "signup.step2.field3": "फ़ोन नंबर (देश कोड के साथ)",
    "signup.step2.field4": "पासवर्ड (कम से कम 8 अक्षर, अक्षरों, संख्याओं और प्रतीकों का मिश्रण)",
    "signup.step2.field5": "पता (आपका प्राथमिक व्यवसाय या निवास पता)",
    "signup.step3.title": "चरण 3: अपना उपयोगकर्ता भूमिका चुनें",
    "signup.step3.description": "वह भूमिका चुनें जो आपको सबसे अच्छी तरह से वर्णन करती है:",
    "signup.step3.role1.title": "किसान",
    "signup.step3.role1.description": "यदि आप फसलें उगाना और बेचना चाहते हैं या कृषि अनुबंधों में प्रवेश करना चाहते हैं",
    "signup.step3.role2.title": "खरीदार",
    "signup.step3.role2.description": "यदि आप किसानों से कृषि उत्पाद खरीदते हैं",
    "signup.step3.role3.title": "एजेंट",
    "signup.step3.role3.description": "यदि आप किसानों और खरीदारों के बीच लेनदेन को सुविधाजनक बनाते हैं",
    "signup.step4.title": "चरण 4: अपना खाता बनाएं",
    "signup.step4.description": 'अपनी जानकारी जमा करने के लिए "खाता बनाएं" बटन पर क्लिक करें। आप सत्यापन पेज पर पुनर्निर्देशित किए जाएंगे।',
    "login.title": "अपने खाते में लॉग इन करें",
    "login.description": "लॉग इन करके अपने कृषि अनुबंध डैशबोर्ड तक पहुंचें",
    "login.step1.title": "चरण 1: लॉग इन पेज पर जाएं",
    "login.step1.description": 'वेबसाइट के शीर्ष नेविगेशन बार में "लॉग इन" बटन पर क्लिक करें।',
    "login.step2.title": "चरण 2: अपनी साख दर्ज करें",
    "login.step2.description": "अपना पंजीकृत ईमेल पता और पासवर्ड संबंधित फ़ील्ड में दर्ज करें।",
    "login.step2.tip": 'यदि आप अपना पासवर्ड भूल गए हैं, तो इसे रीसेट करने के लिए "पासवर्ड भूल गए?" लिंक पर क्लिक करें।',
    "login.step3.title": "चरण 3: अपने डैशबोर्ड तक पहुंचें",
    "login.step3.description": "सफलतापूर्वक लॉग इन करने के बाद, आप अपनी उपयोगकर्ता भूमिका के आधार पर अपने व्यक्तिगत डैशबोर्ड पर पुनर्निर्देशित किए जाएंगे।",
  },
  telugu: {
    "guide.title": "వినియోక్తా గైడ్",
    "guide.welcome": "మా సమగ్ర వినియోక్తా గైడ్‌కి స్వాగతం. మా ప్లాట్‌ఫారమ్ యొక్క అన్ని లక్షణాలను ఉపయోగించడం నేర్చుకోండి.",
    "tab.signup": "సైన్ అప్",
    "tab.login": "లాగిన్",
    "tab.contracts": "ఒప్పందాలు",
    "tab.marketplace": "మార్కెట్",
    "tab.negotiation": "చర్చ",
    "tab.transactions": "లావాదేవీలు",
    "tab.profile": "ప్రొఫైల్",
    "tab.verification": "ధృవీకరణ",
    "guide.next": "తదుపరి",
    "language.english": "ఆంగ్లం",
    "language.tamil": "తమిళం",
    "language.hindi": "హిందీ",
    "language.telugu": "తെలുగു",
    "language.kannada": "కన്నడ",
    "language.malayalam": "మలయాళం",
    "Select Language": "భాషను ఎంచుకోండి",
    "signup.title": "ఖాతా సృష్టించడం",
    "signup.description": "మీ వ్యవసాయ ఒప్పంద ఖాతాను సృష్టించడానికి ఈ దశలను అనుసరించండి",
    "signup.step1.title": "దశ 1: సైన్ అప్ పేజీకి వెళ్లండి",
    "signup.step1.description": 'వెబ్‌సైట్ టాప్ నావిగేషన్ బార్‌లో "సైన్ అప్" బటన్‌పై క్లిక్ చేయండి.',
    "signup.step1.tip": "మీరు నేరుగా సైన్ అప్ పేజీకి ప్రాప్యత పొందవచ్చు",
    "signup.step2.title": "దశ 2: మీ వ్యక్తిగత సమాచారాన్ని నింపండి",
    "signup.step2.description": "సైన్ అప్ ఫారమ్‌లో అగత్యవిరువ ఎల్లా ఫీల్డ్‌లను నింపండి:",
    "signup.step2.field1": "పూర్తి పేరు (మీ అధికృత దాఖలెగళలో కాణించే విధంగా)",
    "signup.step2.field2": "ఇమెయిల్ విలాసం (నీవు తర్వాత స్థిరీకరించేది)",
    "signup.step2.field3": "ఫೋన్ సంఖ్యె (దేశ కోడ్‌తో)",
    "signup.step2.field4": "పాస్‌వర్డ్ (కనిష్ఠ 8 అక్షరాలు, అక్షరాలు, సంఖ్యలు మత్తు చిహ్నాల కలయిక)",
    "signup.step2.field5": "విలాసం (మీ ప్రాథమిక వ్యాపార అథవా నివాస విలాసం)",
    "signup.step3.title": "దశ 3: మీ వినియోక్తా పాత్రను ఎంచుకోండి",
    "signup.step3.description": "మిమ్మల్ని ఉత్తమంగా వర్ణించే సరియాద పాత్రను ఎంచుకోండి:",
    "signup.step3.role1.title": "రైతు",
    "signup.step3.role1.description": "నీవు విళకలు వళరించి విలాట చేయాలో లేదా కారషిక కరాఱులో ప్రవేశించాలో",
    "signup.step3.role2.title": "వాఙ్ఙున్నయాలు",
    "signup.step3.role2.description": "నీవు రైతరిందు కారషిక ఉత్పన్నఙ్ఙ౾ వాఙ్ఙాలో",
    "signup.step3.role3.title": "ఏజన్ఱ్",
    "signup.step3.role3.description": "నీవు రైతరిగె మత్తు వాఙ్ఙున్నయాళ్లకు నడువు లావాదేవీలను సులభగొళిస్తే",
    "signup.step4.title": "దశ 4: మీ ఖాతాను సృష్టించండి",
    "signup.step4.description": 'మీ మాహితియన్ని సల్లిసలు "ఖాతా సృష్టించు" బటన్ క్లిక్ చేయండి. మీరు స్థిరీకరణ పేజీకి తిరిచേయయ്యప്పെటുం.',
    "login.title": "మీ ఖాతాలోకి ప్రవేశించండి",
    "login.description": "ప్రవేశించున్నతిలో మీ కారషిక కరార్ డాష్‌బోర్డ్‌కి ప్రవేశ పొందండి",
    "login.step1.title": "దశ 1: లాగిన్ పేజీకి వెళ్లండి",
    "login.step1.description": 'వెబ్‌సైట్ మేలిన న్యావిగేషన్ బార్‌నల్లి "లాగిన్" బటన్ క్లిక్ చేయండి.',
    "login.step2.title": "దశ 2: మీ దృఢీకరణగళన్ని నమోదించండి",
    "login.step2.description": "మీ నోందాయిత ఇమెయిల్ విలాసవుం పాస్‌వర్డ్ అనుబన്ధ ఫీల్డ్లలో నమోదించండి.",
    "login.step2.tip": 'మీరు పాస్‌వర్డ్ మరెతిది ఉంటే, అదన్ని రీసెట್ చేయడానికి "పాస్‌వర్డ్ మరెతిదీరా?" లింక് క్లిక్ చేయండి.',
    "login.step3.title": "దశ 3: మీ డాష്‌బోర్డ്‌కి ప్రవేశ పొందండి",
    "login.step3.description": "యశస్వియాగి ప్రవేశిసిన శേషం, మీ వినియోక్తా పాత్రవన്ని అటిస్థానమాక్కి మీ వ్యక్తిగత డాష്‌బోర్డ്‌కి నీవు తిరిచേయయ్యప്పు",
  },
  kannada: {
    "guide.title": "ಬಳಕെದಾರ ಮಾರ್ಗದರ್ಶಿ",
    "guide.welcome": "ನಮ್ಮ ಸಮಗ್ರ ಬಳಕെದಾರ ಮಾರ್ಗದರ್ಶಿಗೆ ಸ್ವಾಗತ. ನಮ್ಮ ವೇದಿಕೆಯ ಎಲ್ಲಾ ವೈಶಿಷ್ಟ್ಯಗಳು ಬಳಸಲು ಕಲಿಯಿರಿ.",
    "tab.signup": "ಸೈನ್ ಅಪ್",
    "tab.login": "ಲಾಗಿನ್",
    "tab.contracts": "ಒಪ್ಪಂದಗಳು",
    "tab.marketplace": "ಮಾರುಕಟ್ಟೆ",
    "tab.negotiation": "ಸಂಧಾನ",
    "tab.transactions": "ವಹಿವಾಟುಗಳು",
    "tab.profile": "ಪ్ರೊಫೈಲ್",
    "tab.verification": "ಪರಿಶೀಲನೆ",
    "guide.next": "ಮುಂದೆ",
    "language.english": "ಆಂಗ್ಲ",
    "language.tamil": "ತಮಿಳು",
    "language.hindi": "ಹಿಂದಿ",
    "language.telugu": "ತെಲುಗു",
    "language.kannada": "ಕನ್ನಡ",
    "language.malayalam": "ಮಲಯಾಳಂ",
    "Select Language": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "signup.title": "ಖಾತೆ ರಚಿಸುವಿಕೆ",
    "signup.description": "ನಿಮ್ಮ ಕೃಷಿ ಒಪ್ಪಂದ ಖಾತೆಯನ್ನು ರಚಿಸಲು ಈ ಹಂತಗಳನ್ನು ಅನುಸರಿಸಿ",
    "signup.step1.title": "ಹಂತ 1: ಸೈನ್ ಅಪ್ ಪುಟಕ್ಕೆ ಹೋಗಿ",
    "signup.step1.description": 'ವೆಬ್‌ಸೈట್ ಮೇಲಿನ ನ್ಯಾವಿಗೇಷನ్ ಬಾರ್‌ನಲ್ಲಿ "ಸೈನ್ ಅಪ್" ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    "signup.step1.tip": "ನೀವು ನೇರವಾಗಿ ಸೈನ್ ಅಪ್ ಪುಟಕ್ಕೆ ಪ್ರವೇಶಿಸಬಹುದು",
    "signup.step2.title": "ಹಂತ 2: ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ಭರ್ತಿ ಮಾಡಿ",
    "signup.step2.description": "ಸೈನ್ ಅಪ್ ಫಾರ್ಮ್‌ನಲ್ಲಿ ಅಗత್ಯವಿరువ ಎಲ్లಾ ಫೀೲ್ಡುಕಳನ್ನು ಭರ್ತಿ ಮಾಡಿ:",
    "signup.step2.field1": "ಪೂರ್ಣ ಹೆಸರು (ನಿಮ್ಮ ಅಧಿಕೃತ ದಾಖಲೆಗಳಲ್ಲಿ ಕಾಣಿಸುವಂತೆ)",
    "signup.step2.field2": "ಇಮೇಲ್ ವಿಲಾಸ (ನೀವು ನಂತರ ಸ್ಥಿರೀಕರಿಸುವುದು)",
    "signup.step2.field3": "ಫೋನ್ ಸಂಖ್ಯೆ (ದೇಶ ಕೋಡ್‌ನೊಂದಿಗೆ)",
    "signup.step2.field4": "ಪಾಸ್‌ವೇಡ് (ಕುಱಞ್ಞ 8 ಅಕ್ಷರಗಳು, ಅಕ್ಷರಗಳು, ಸಂಖ್ಯಲು, ಚಿಹ್ನೆಗಳ ಮಿಶ್ರಣ)",
    "signup.step2.field5": "ವಿಲಾಸಂ (ನಿಮ್ಮ ಪ್ರಾಥಮಿಕ ವ್ಯಾಪಾರ ಅಥವಾ ನಿವಾಸ ವಿಲಾಸ)",
    "signup.step3.title": "ಹಂತ 3: ನಿಮ್ಮ ಬಳಕെದಾರ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "signup.step3.description": "ನಿಮ್ಮನ್ನು ಉತ್ತಮವಾಗಿ ವಿವರಿಸುವ ಸರಿಯಾದ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ:",
    "signup.step3.role1.title": "ರೈತ",
    "signup.step3.role1.description": "ನೀವು ವಿಳಕಲು ವಳರಿಸಿ ವಿಲಾಟ ಚೇಯಲು ಬಯಸಿದರೆ ಅಥವಾ ಕಾರಷಿಕ ಕರಾಱುಲ್ಲೋ",
    "signup.step3.role2.title": "ವಾಙ్ಙುನ్ನಯಾಲ್ಲೋ",
    "signup.step3.role2.description": "ನೀವು ರೈತರಿಂದ ಕಾರಷಿಕ ಉತ್ಪನ್ನಗಳನ್ನು ವಾಙ್ಙಾಲ್ಲೋ",
    "signup.step3.role3.title": "ಏಜನ్ಱ్",
    "signup.step3.role3.description": "ನೀವು ರೈತರಿಗೆ ಮತ್ತು ವಾಙ್ಙುನ್ನಯಾಳ್ಲೋ ಇಟುವಾಟುಗಳನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತೇನೆಲ್ಲೋ",
    "signup.step4.title": "ಹಂತ 4: ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ",
    "signup.step4.description": 'ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಸಲ్ಲಿಸಲు "ಖಾತೆ ರಚಿಸಿ" ಬಟನ್ ಕ್ಲಿಕ్ ಮಾಡಿ. ನೀವು ಸ್ಥಿರೀಕರಣ ಪುಟಕ್ಕೆ ತಿರಿಚേಯಯ್ಯಪ್ಪೆಟ್ಟು.',
    "login.title": "ನಿಮ್ಮ ಖಾತೆಗೆ ಪ್ರವೇಶಿಸಿ",
    "login.description": "ಪ್ರವೇಶಿಸುವ ಮೂಲಕ ನಿಮ್ಮ ಕಾರಷಿಕ ಕರಾ೼ ಡಾಷ್‌ಬೋರ್ಡ್‌ಗೆ ಪ್ರವೇಶ ಪಡೆಯಿರಿ",
    "login.step1.title": "ಹಂತ 1: ಲಾಗಿನ್ ಪುಟಕ್ಕೆ ಹೋಗಿ",
    "login.step1.description": 'ವೆಬ್‌ಸೈట್ ಮೇಲಿನ ನ್ಯಾವಿಗೇಷನ్ ಬಾರ್‌ನಲ್ಲಿ "ಲಾಗಿನ್" ಬಟನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.',
    "login.step2.title": "ಹಂತ 2: ನಿಮ್ಮ ದೃಢೀಕರಣಗಳನ್ನು ನಮೂದಿಸಿ",
    "login.step2.description": "ನಿಮ್ಮ ನೋಂದಾಯಿತ ಇಮೇಲ್ ವಿಲಾಸ ಮತ್ತು ಪಾಸ್‌ವೇಡ് ಅನ್ನು ಸಂಬಂಧಿತ ಫೀಲ್ಡ್ಲೋ ನಮೂದಿಸಿ.",
    "login.step2.tip": 'ನೀವು ಪಾಸ್‌ವೇಡ് ಮರೆತಿದ್ದರೆ, ಅದನ್ನು ರೀಸೆಟ್ ಮಾಡಲು "ಪಾಸ್‌ವೇಡ് ಮರೆತಿದ್ದೀರಾ?" ಲಿಂಕ് ಕ್ಲಿಕ్ ಮಾಡಿ.',
    "login.step3.title": "ಹಂತ 3: ನಿಮ್ಮ ಡಾಷ್‌ಬೋರ್ಡ್‌ಗೆ ಪ್ರವೇಶ ಪಡೆಯಿರಿ",
    "login.step3.description": "ಯಶಸ್ವಿಯಾಗಿ ಪ್ರವೇಶಿಸಿದ ನಂತರ, ನಿಮ್ಮ ಬಳಕെದಾರ ಪಾತ್ರವನ್ನು ಆಧರಿಸಿ ನಿಮ್ಮ ವ್ಯಕ്ತಿಗತ ಡಾಷ್‌ಬೋರ್ಡ್‌ಗೆ ನೀವು ತಿರಿಚേಯಯ್ಯಪ್ಪು",
  },
  malayalam: {
    "guide.title": "ഉപയോക്തൃ ഗైഡ്",
    "guide.welcome": "ഞങ്ങളുടെ സമഗ്ര ഉപയോക്തൃ ഗైഡിലേക്ക് സ్വാഗതം",
    "tab.signup": "സൈൻ അപ്പ്",
    "tab.login": "ലോഗിൻ",
    "tab.contracts": "കരാറുകൾ",
    "tab.marketplace": "മാർക്കറ്റ്",
    "tab.negotiation": "ചർച്ച",
    "tab.transactions": "ഇടപാടുകൾ",
    "tab.profile": "പ్രൊഫൈൽ",
    "tab.verification": "പരിശോധന",
    "guide.next": "അടുത്തത്",
    "language.english": "ഇംഗ്ലീഷ്",
    "language.tamil": "തമിഴ്",
    "language.hindi": "ഹിന്ദി",
    "language.telugu": "തെലുങ്ക്",
    "language.kannada": "കന്നഡ",
    "language.malayalam": "മലയാളം",
    "Select Language": "ഭാഷ തിരഞ്ഞെടുക്കുക",
    "signup.title": "അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു",
    "signup.description": "നിങ്ങളുടെ കാർഷിക കരാർ അക്കൗണ്ട് സൃഷ്ടിക്കാൻ ഈ ഘട്ടങ്ങൾ പിന്തുടരുക",
    "signup.step1.title": "ഘട്ടം 1: സൈൻ അപ്പ് പേജിലേക്ക് പോകുക",
    "signup.step1.description": 'വെബ്സൈറ്റ് മുകളിലെ നാവിഗേഷൻ ബാറിൽ "സൈൻ അപ്പ്" ബട്ടൺ ക്ലിക്ക് ചെയ്യുക.',
    "signup.step1.tip": "നിങ്ങൾക്ക് നേരിട്ട് സൈൻ അപ്പ് പേജിലേക്ക് പോകാം",
    "signup.step2.title": "ഘട്ടം 2: നിങ്ങളുടെ വ്യക്തിഗത വിവരങ്ങൾ പൂരിപ്പിക്കുക",
    "signup.step2.description": "സൈൻ അപ്പ് ഫോമിൽ അഗത്യവിരുവ എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക:",
    "signup.step2.field1": "പൂർണ്ണമായ പേര് (നിങ്ങളുടെ ഔദ്യോഗിക രേഖകളിൽ കാണുന്നതുപോലെ)",
    "signup.step2.field2": "ഇമെയിൽ വിലാസം (നೀവു പിന്നീട് സ്ഥിരീകരിക്കേണ്ടത്)",
    "signup.step2.field3": "ഫോന് സംഖ്യെ (ദേശ കോഡ് ഉൾപ്പെടെ)",
    "signup.step2.field4": "പാസ്വേഡ് (കുറഞ്ഞത് 8 അക്ഷരങ്ങൾ, അക്ഷരങ്ങൾ, സംഖ്യകൾ, ചിഹ്നങ്ങൾ എന്നിവയുടെ കൂട്ടിച്ചേർക്കൽ)",
    "signup.step2.field5": "വിലാസം (നിങ്ങളുടെ പ്രാഥമിക വ്യാപാര അഥവാ നിവാസ വിലാസം)",
    "signup.step3.title": "ഘട്ടം 3: നിമ്മ ഉപയോക്തൃ പാത്രവന്നു ആയ്കെമാഡി",
    "signup.step3.description": "നിമ്മന್നു ഉത്തമവാഗി വിവരിക്കുന്ന സരിയായ പാത്രവന്നു ആയ്കെമാഡി:",
    "signup.step3.role1.title": "രൈത്",
    "signup.step3.role1.description": "നീവു വിളകൾ വളർത്തി വിലാട്ട ചേയാലോ അഥവാ കാരഷിക കരാറുലോ",
    "signup.step3.role2.title": "വാങ്ങുന്നയാലോ",
    "signup.step3.role2.description": "നീവു രൈതരിംദു കാരഷിക ഉത്പന്നങ്ങൾ വാങ്ങാലോ",
    "signup.step3.role3.title": "ഏജന്റ്",
    "signup.step3.role3.description": "നീവു രൈതരിഗെ മത്തു വാങ്ങുന്നയാളോ ഇടുവാടുകളന്നു സുലഭഗൊളിസ്തേനോ",
    "signup.step4.title": "ഘട്ടം 4: നിമ്മ ഖാതെയുടെ സൃഷ്ടിക്കുക",
    "signup.step4.description": 'നിമ്മ മാഹിതിയുടെ സല్ലിസലు "ഖാതെ സൃഷ്ടിക്കുക" ബട്ടൺ ക്ലിക്ക് ചേയ്യുക. നീവു സ്ഥിരീകരണ പുടക്കെ തിരിച്ചയയ്ക്കപ്പെടും.',
    "login.title": "നിമ്മ ഖാതെയുടെ പ്രവേശിക്കുക",
    "login.description": "പ്രവേശിക്കുന്നതിലൂടെ നിമ്മ കാരഷിക കരാർ ഡാഷ്‌ബോർഡ്‌കെ പ്രവേശ നേടുക",
    "login.step1.title": "ഘട്ടം 1: ലാഗിന് പേജിലേക്ക് പോകുക",
    "login.step1.description": 'വെബ്സൈറ്റ് മേലിന നാവിഗേഷൻ ബാറിൽ "ലാഗിന്" ബട്ടൺ ക്ലിക്ക് ചേയ്യുക.',
    "login.step2.title": "ഘട്ടം 2: നിമ്മ ദൃഢീകരണഗളന്നു നമൂദിസി",
    "login.step2.description": "നിമ്മ നോംദായിത ഇമെയില് വിലാസവും പാസ്വേഡ് അനുബന്ധ ഫീല്ഡുകളലോ നമൂദിസി.",
    "login.step2.tip": 'നീവു പാസ്വേഡ് മറന്നുപോയെങ്കിൽ, അത് റീസെറ്റ് ചേയ്യാലോ "പാസ്വേഡ് മറന്നുപോയോ?" ലിങ്ക് ക്ലിക്ക് ചേയ്യുക.',
    "login.step3.title": "ഘട്ടം 3: നിമ്മ ഡാഷ്‌ബോർഡ്‌കെ പ്രവേശ നേടുക",
    "login.step3.description": "യശസ്വിയാഗി പ്രവേശിസിന ശേഷം, നിമ്മ ഉപയോക്തൃ പാത്രവനെ അടിസ്ഥാനമാക്കി നിമ്മ വ്യക്തിഗത ഡാഷ്‌ബോർഡ്‌കെ നീവു തിരിച്ചയയ്ക്കപ്പെടും.",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("english")

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]]
    if (!translation) {
      console.warn(`Missing translation for key "${key}" in language "${language}"`)
      // Return a more user-friendly fallback message
      return `[${language.toUpperCase()}] ${key}`
    }
    return translation
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
} 